### ISSUE TITLE
Indexing time with lists

### ISSUE THREAD

**Issue by fmaussion** [pydata/xarray#1418]
Is this a bug? Look the following example:

```python
ds = xr.tutorial.load_dataset('air_temperature')

ds.sel(time='2013-01-01T00:00')   # works fine
[output removed]

ds.sel(time=['2013-01-01T00:00'])   # errors
Traceback (most recent call last):
  File "/home/mowglie/.pycharm-community-2017.1/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/mowglie/Documents/git/xarray-official/xarray/core/dataset.py", line 1206, in sel
    self, indexers, method=method, tolerance=tolerance
  File "/home/mowglie/Documents/git/xarray-official/xarray/core/indexing.py", line 290, in remap_label_indexers
    dim, method, tolerance)
  File "/home/mowglie/Documents/git/xarray-official/xarray/core/indexing.py", line 229, in convert_label_indexer
    % index_name)
KeyError: "not all values found in index 'time'"
```

**Comment by shoyer** [comment]
Pandas actually works the same way (and we simply forward to pandas's functionality here). I'm not entirely sure why -- it might be worth raising over there.

**Comment by shoyer** [comment]
Note that you can index with a list of datetime/datetime64 objects, just not strings. Possibly this has something to do with how a single string can be interpreted as selecting a range of times.
