### ISSUE TITLE
xarray.plot.imshow with datetime coordinates results in blank plot

### ISSUE THREAD

**Issue by gerritholl** [pydata/xarray#1435]
```
In [72]: da = xarray.DataArray(arange(5*6).reshape(5,6), dims=("A", "B"), coords={"A": arange(5), "B": pd.date_range("2000-01-01", periods=6)})

In [73]: da.plot.imshow()
Out[73]: <matplotlib.image.AxesImage at 0x7f699cf1acf8>
```

The resulting plot has the correct axes and colorbar, but the contents of the plot itself are blank.  Upon moving the cursor over the plot, there is an exception in `Tkinter`:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/users/gholl/lib/python3.5/tkinter/__init__.py", line 1549, in __call__
    return self.func(*args)
  File "/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 387, in motion_notify_event
    FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
  File "/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 1966, in motion_notify_event
    self.callbacks.process(s, event)
  File "/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/matplotlib/cbook.py", line 554, in process
    proxy(*args, **kwargs)
  File "/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/matplotlib/cbook.py", line 416, in __call__
    return mtd(*args, **kwargs)
  File "/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2857, in mouse_move
    artists = [a for a in event.inaxes.mouseover_set
  File "/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2858, in <listcomp>
    if a.contains(event) and a.get_visible()]
  File "/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/matplotlib/image.py", line 567, in contains
    inside = ((x >= xmin) and (x <= xmax) and
TypeError: invalid type promotion
```

**Comment by shoyer** [comment]
I get a different error when I try this in a notebook (using matplotlib 1.5.x):
```
<matplotlib.image.AxesImage at 0xaba8910>Error in callback <function post_execute at 0x7eed0c8> (for post_execute):
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
.../matplotlib/pyplot.py in post_execute()
    145             def post_execute():
    146                 if matplotlib.is_interactive():
--> 147                     draw_all()
    148 
    149             # IPython >= 2

.../matplotlib/_pylab_helpers.py in draw_all(cls, force)
    148         for f_mgr in cls.get_all_fig_managers():
    149             if force or f_mgr.canvas.figure.stale:
--> 150                 f_mgr.canvas.draw_idle()
    151 
    152 atexit.register(Gcf.destroy_all)

.../matplotlib/backend_bases.py in draw_idle(self, *args, **kwargs)
   2024         if not self._is_idle_drawing:
   2025             with self._idle_draw_cntx():
-> 2026                 self.draw(*args, **kwargs)
   2027 
   2028     def draw_cursor(self, event):

.../matplotlib/backends/backend_agg.py in draw(self)
    472 
    473         try:
--> 474             self.figure.draw(self.renderer)
    475         finally:
    476             RendererAgg.lock.release()

.../matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     60     def draw_wrapper(artist, renderer, *args, **kwargs):
     61         before(artist, renderer)
---> 62         draw(artist, renderer, *args, **kwargs)
     63         after(artist, renderer)
     64 

.../matplotlib/figure.py in draw(self, renderer)
   1157         dsu.sort(key=itemgetter(0))
   1158         for zorder, a, func, args in dsu:
-> 1159             func(*args)
   1160 
   1161         renderer.close_group('figure')

.../matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     60     def draw_wrapper(artist, renderer, *args, **kwargs):
     61         before(artist, renderer)
---> 62         draw(artist, renderer, *args, **kwargs)
     63         after(artist, renderer)
     64 

.../matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2317 
   2318         for zorder, a in dsu:
-> 2319             a.draw(renderer)
   2320 
   2321         renderer.close_group('axes')

.../matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     60     def draw_wrapper(artist, renderer, *args, **kwargs):
     61         before(artist, renderer)
---> 62         draw(artist, renderer, *args, **kwargs)
     63         after(artist, renderer)
     64 

.../matplotlib/image.py in draw(self, renderer, *args, **kwargs)
    387                               " correctly with this backend.")
    388 
--> 389             im = self.make_image(renderer.get_image_magnification())
    390             if im is None:
    391                 return

.../matplotlib/image.py in make_image(self, magnification)
    612         trans = self.get_transform()
    613         xy = trans.transform(np.array([(x1, y1),
--> 614                                        (x2, y2),
    615                                        ]))
    616         _x1, _y1 = xy[0]

.../matplotlib/transforms.py in transform(self, values)
   1311 
   1312         # Transform the values
-> 1313         res = self.transform_affine(self.transform_non_affine(values))
   1314 
   1315         # Convert the result back to the shape of the input values.

.../matplotlib/transforms.py in transform_affine(self, points)
   2348 
   2349     def transform_affine(self, points):
-> 2350         return self.get_affine().transform(points)
   2351     transform_affine.__doc__ = Transform.transform_affine.__doc__
   2352 

.../matplotlib/transforms.py in transform(self, values)
   1663 
   1664     def transform(self, values):
-> 1665         return self.transform_affine(values)
   1666     transform.__doc__ = Transform.transform.__doc__
   1667 

.../matplotlib/transforms.py in transform_affine(self, points)
   1747             tpoints = affine_transform(points.data, mtx)
   1748             return ma.MaskedArray(tpoints, mask=ma.getmask(points))
-> 1749         return affine_transform(points, mtx)
   1750 
   1751     def transform_point(self, point):

ValueError: object too deep for desired array
```

Certainly fixes would be welcome here, though it might be somewhat involved -- and might possibly require upstream fixes in matplotlib (I'm really not sure).

**Comment by Phibedy** [comment]
Maybe not related at all, maybe it helps. I am getting the same error for a different backend. https://github.com/matplotlib/matplotlib/issues/10617

**Comment by keewis** [comment]
this is still an issue

**Comment by dcherian** [comment]
This now raises TypeError. Upstream issue is https://github.com/matplotlib/matplotlib/issues/22105
```
File ~/mambaforge/envs/dcpy/lib/python3.8/site-packages/matplotlib/axes/_base.py:2476, in _AxesBase.update_datalim(self, xys, updatex, updatey)
   2458 """
   2459 Extend the `~.Axes.dataLim` Bbox to include the given points.
   2460 
   (...)
   2473     Whether to update the x/y limits.
   2474 """
   2475 xys = np.asarray(xys)
-> 2476 if not np.any(np.isfinite(xys)):
   2477     return
   2478 self.dataLim.update_from_data_xy(xys, self.ignore_existing_data_limits,
   2479                                  updatex=updatex, updatey=updatey)

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by kmuehlbauer** [comment]
Can't reproduce with latest xarray and matplotlib. Please reopen or open a new issue with updated MCVE. Thanks!
