### ISSUE TITLE
AttributeError: '<class 'pydap.model.GridType'>' object has no attribute 'shape'

### ISSUE THREAD

**Issue by ererkka** [pydata/xarray#1857]
#### Code Sample, a copy-pastable example if possible

```python
import xarray as xa
from pydap.cas.urs import setup_session
url = 'https://goldsmr4.gesdisc.eosdis.nasa.gov/dods/M2T1NXFLX'
session = setup_session(username='****', password='****', check_url=url)
store = xa.backends.PydapDataStore.open(url, session=session)
ds = xa.open_dataset(store)
```
#### Problem description

I was trying to connect to NASA MERRA-2 data through OPeNDAP, following the documentation here: http://xarray.pydata.org/en/stable/io.html#OPeNDAP. I was able to get through a previous bug (#1775) by installing the latest master version of xarray.

#### Expected Output

Expecting the collection (M2T1NXFLX) content to show up as an xarray dataset.

#### Output of ``xr.show_versions()``

<pre>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

xarray: 0.10.0+dev44.g0a0593d
pandas: 0.22.0
numpy: 1.14.0
scipy: 1.0.0
netCDF4: None
h5netcdf: None
Nio: None
zarr: None
bottleneck: None
cyordereddict: None
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
setuptools: 38.4.0
pip: 9.0.1
conda: None
pytest: None
IPython: None
sphinx: None
</pre>

**Comment by fujiisoup** [comment]
I couldn't reproduce it (I guess I need a userid and password to access the data).
Can you try this?

```python
url = 'http://test.opendap.org/opendap/hyrax/data/nc/bears.nc'
actual = xr.open_dataset(url, engine='pydap')
```

**Comment by ererkka** [comment]
Same thing:
```
Traceback (most recent call last):
  File "C:\Anaconda3\envs\xa_test\lib\site-packages\pydap\model.py", line 295, in __getattr__
    return self[attr]
  File "C:\Anaconda3\envs\xa_test\lib\site-packages\pydap\model.py", line 556, in __getitem__
    return StructureType.__getitem__(self, key)
  File "C:\Anaconda3\envs\xa_test\lib\site-packages\pydap\model.py", line 326, in __getitem__
    return self._dict[key]
KeyError: 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\xa_test\lib\site-packages\pydap\model.py", line 180, in __getattr__
    return self.attributes[attr]
KeyError: 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\src\xarray\xarray\backends\api.py", line 305, in open_dataset
    return maybe_decode_store(store, lock)
  File "c:\src\xarray\xarray\backends\api.py", line 225, in maybe_decode_store
    drop_variables=drop_variables)
  File "c:\src\xarray\xarray\conventions.py", line 598, in decode_cf
    vars, attrs = obj.load()
  File "c:\src\xarray\xarray\backends\common.py", line 133, in load
    for k, v in self.get_variables().items())
  File "c:\src\xarray\xarray\backends\pydap_.py", line 85, in get_variables
    for k in self.ds.keys())
  File "c:\src\xarray\xarray\core\utils.py", line 309, in FrozenOrderedDict
    return Frozen(OrderedDict(*args, **kwargs))
  File "c:\src\xarray\xarray\backends\pydap_.py", line 85, in <genexpr>
    for k in self.ds.keys())
  File "c:\src\xarray\xarray\backends\pydap_.py", line 79, in open_store_variable
    data = indexing.LazilyIndexedArray(PydapArrayWrapper(var))
  File "c:\src\xarray\xarray\core\indexing.py", line 482, in __init__
    key = BasicIndexer((slice(None),) * array.ndim)
  File "c:\src\xarray\xarray\core\utils.py", line 428, in ndim
    return len(self.shape)
  File "c:\src\xarray\xarray\backends\pydap_.py", line 20, in shape
    return self.array.shape
  File "C:\Anaconda3\envs\xa_test\lib\site-packages\pydap\model.py", line 297, in __getattr__
    return DapType.__getattr__(self, attr)
  File "C:\Anaconda3\envs\xa_test\lib\site-packages\pydap\model.py", line 184, in __getattr__
    % (self.__class__, attr))
AttributeError: '<class 'pydap.model.GridType'>' object has no attribute 'shape'
```

**Comment by fujiisoup** [comment]
It looks like you are using the older version than #1775.
Could you try this again?
```
git pull
git checkout master
python setup.py develop
```

**Comment by ererkka** [comment]
After pulling (Git says ‘Already up-to-date.’), my xarray version (`xarray.__version__`) is still '0.10.0+dev44.g0a0593d'. What version are you using?

**Comment by fujiisoup** [comment]
I'm also using the same commit version.

Can you try to update pydap?
#1775 was caused by the update of pydap. This issue might be also.

**Comment by ererkka** [comment]
Thanks for the suggestion! Installing both latest master of xarray (0092911) and latest master of pydap (4ae73e3) fixed this issue, and now I can open the dataset.
