### ISSUE TITLE
`AttributeError: 'DataArray' object has no attribute 'ravel'` when using `np.intersect1d(..., assume_unique=True)`

### ISSUE THREAD

**Issue by chrisbarber** [pydata/xarray#2371]
#### Code Sample, a copy-pastable example if possible

```python
>>> import xarray as xr
>>> import numpy as np
>>> np.intersect1d(xr.DataArray(np.empty(5), dims=('a',)), xr.DataArray(np.empty(5), dims=('a',)))
array([2.37151510e-322, 6.92748216e-310])
>>> np.intersect1d(xr.DataArray(np.empty(5), dims=('a',)), xr.DataArray(np.empty(5), dims=('a',)), assume_unique=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local1/opt/miniconda3/envs/datacube/lib/python3.6/site-packages/numpy/lib/arraysetops.py", line 368, in intersect1d
    ar1 = ar1.ravel()
  File "/local1/opt/miniconda3/envs/datacube/lib/python3.6/site-packages/xarray/core/common.py", line 176, in __getattr__
    (type(self).__name__, name))
AttributeError: 'DataArray' object has no attribute 'ravel'
```
#### Problem description

I believe this worked in a previous version, not sure what might have changed. But I don't see any reason calling `np.intersect1d` on DataArray's shouldn't work, or why `assume_unique=True` ought to make any difference.

#### Expected Output

Output should be the same as calling `intersect1d` with `assume_unique=True` directly on ndarray's. E.g.
```python
>>> np.intersect1d(xr.DataArray(np.empty(5), dims=('a',)).values, xr.DataArray(np.empty(5), dims=('a',)).values, assume_unique=True)
array([2.37151510e-322, 6.94714805e-310])
```

#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-514.26.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.8
pandas: 0.23.4
numpy: 1.15.0
scipy: 1.1.0
netCDF4: None
h5netcdf: 0.6.1
h5py: 2.8.0
Nio: None
zarr: 2.2.0
bottleneck: None
cyordereddict: None
dask: 0.18.2
distributed: 1.22.0
matplotlib: 2.2.3
cartopy: None
seaborn: None
setuptools: 40.0.0
pip: 18.0
conda: None
pytest: None
IPython: None
sphinx: None
</details>

**Comment by shoyer** [comment]
It looks like this changed in NumPy 1.15 which changed `intersect1d` -- could you kindly report the bug upstream?

**Comment by charris** [comment]
@shoyer Does DataArray subclass ndarray? We can make some fixes in NumPy, but I'd like to know what we are trying to support here. In particular, we should have a test for anything we decide needs to be supported into the future, and this sounds a bit like a special case.

**Comment by charris** [comment]
I'm also curious if DataArray supports the common indices enhancement that led to this problem.

**Comment by shoyer** [comment]
DataArray does not subclass ndarray. It's just a class that implements `__array__` but not `ravel()`. So really `np.intersect1d()` should just be careful to always call `np.asarray()` internally, which it was doing before in an implicit way.
