### ISSUE TITLE
Error importing xarray 0.11.2 in python 2.7

### ISSUE THREAD

**Issue by xylar** [pydata/xarray#2680]
I'm creating a fresh conda environment that's pretty minimal:
```bash
conda create -y -n test_env python=2.7 xarray numpy dask
conda activate test_env
python -c "import xarray"
```
I see the following error message:
<details>
  <p>

```
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xylar/miniconda3/envs/test_env4/lib/python2.7/site-packages/xarray/__init__.py", line 10, in <module>
    from .core.alignment import align, broadcast, broadcast_arrays
  File "/home/xylar/miniconda3/envs/test_env4/lib/python2.7/site-packages/xarray/core/alignment.py", line 10, in <module>
    from . import utils
  File "/home/xylar/miniconda3/envs/test_env4/lib/python2.7/site-packages/xarray/core/utils.py", line 16, in <module>
    from .pycompat import (
  File "/home/xylar/miniconda3/envs/test_env4/lib/python2.7/site-packages/xarray/core/pycompat.py", line 73, in <module>
    import dask.array
  File "/home/xylar/miniconda3/envs/test_env4/lib/python2.7/site-packages/dask/array/__init__.py", line 9, in <module>
    from .routines import (take, choose, argwhere, where, coarsen, insert,
  File "/home/xylar/miniconda3/envs/test_env4/lib/python2.7/site-packages/dask/array/routines.py", line 256, in <module>
    @wraps(np.matmul)
  File "/home/xylar/miniconda3/envs/test_env4/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute '__module__'
```
  </p>
</details>

If I omit `dask`, I don't see this error.  I also haven't had any trouble before this week so it's possible that this is caused indirectly by another library having been updated.

#### Expected Output

Nothing at all.

#### Details of conda environment
<details>
 <summary>Details from conda create</summary>
  <p>

```
  conda create -n test_env4 python=2.7 xarray numpy dask
  Solving environment: done

  ## Package Plan ##

  environment location: /home/xylar/miniconda3/envs/test_env4

  added / updated specs: 
    - dask
    - numpy
    - python=2.7
    - xarray


  The following NEW packages will be INSTALLED:

    backports_abc:    0.5-py_1                               conda-forge
    blas:             1.1-openblas                           conda-forge
    bokeh:            1.0.4-py27_1000                        conda-forge
    ca-certificates:  2018.11.29-ha4d7672_0                  conda-forge
    certifi:          2018.11.29-py27_1000                   conda-forge
    click:            7.0-py_0                               conda-forge
    cloudpickle:      0.6.1-py_0                             conda-forge
    cytoolz:          0.9.0.1-py27h14c3975_1001              conda-forge
    dask:             1.0.0-py_0                             conda-forge
    dask-core:        1.0.0-py_0                             conda-forge
    distributed:      1.25.2-py27_1000                       conda-forge
    freetype:         2.9.1-h3cfcefd_1004                    conda-forge
    futures:          3.2.0-py27_1000                        conda-forge
    heapdict:         1.0.0-py27_1000                        conda-forge
    jinja2:           2.10-py_1                              conda-forge
    jpeg:             9c-h14c3975_1001                       conda-forge
    libffi:           3.2.1-hf484d3e_1005                    conda-forge
    libgcc-ng:        7.3.0-hdf63c60_0                       conda-forge
    libgfortran-ng:   7.2.0-hdf63c60_3                       conda-forge
    libpng:           1.6.36-h84994c4_1000                   conda-forge
    libstdcxx-ng:     7.3.0-hdf63c60_0                       conda-forge
    libtiff:          4.0.10-h648cc4a_1001                   conda-forge
    locket:           0.2.0-py_2                             conda-forge
    markupsafe:       1.1.0-py27h14c3975_1000                conda-forge
    msgpack-python:   0.6.0-py27h6bb024c_1000                conda-forge
    ncurses:          6.1-hf484d3e_1002                      conda-forge
    numpy:            1.16.0-py27_blas_openblash1522bff_1000 conda-forge [blas_openblas]
    olefile:          0.46-py_0                              conda-forge
    openblas:         0.3.3-h9ac9557_1001                    conda-forge
    openssl:          1.0.2p-h14c3975_1002                   conda-forge
    packaging:        18.0-py_0                              conda-forge
    pandas:           0.24.0rc1-py27hf484d3e_0               conda-forge
    partd:            0.3.9-py_0                             conda-forge
    pillow:           5.4.1-py27h00a061d_1000                conda-forge
    pip:              18.1-py27_1000                         conda-forge
    psutil:           5.4.8-py27h14c3975_1000                conda-forge
    pyparsing:        2.3.1-py_0                             conda-forge
    python:           2.7.15-h938d71a_1006                   conda-forge
    python-dateutil:  2.7.5-py_0                             conda-forge
    pytz:             2018.9-py_0                            conda-forge
    pyyaml:           3.13-py27h14c3975_1001                 conda-forge
    readline:         7.0-hf8c457e_1001                      conda-forge
    setuptools:       40.6.3-py27_0                          conda-forge
    singledispatch:   3.4.0.3-py27_1000                      conda-forge
    six:              1.12.0-py27_1000                       conda-forge
    sortedcontainers: 2.1.0-py_0                             conda-forge
    sqlite:           3.26.0-h67949de_1000                   conda-forge
    tblib:            1.3.2-py_1                             conda-forge
    tk:               8.6.9-h84994c4_1000                    conda-forge
    toolz:            0.9.0-py_1                             conda-forge
    tornado:          5.1.1-py27h14c3975_1000                conda-forge
    wheel:            0.32.3-py27_0                          conda-forge
    xarray:           0.11.2-py27_1000                       conda-forge
    xz:               5.2.4-h14c3975_1001                    conda-forge
    yaml:             0.1.7-h14c3975_1001                    conda-forge
    zict:             0.1.3-py_0                             conda-forge
    zlib:             1.2.11-h14c3975_1004                   conda-forge

  Proceed ([y]/n)? y

  Preparing transaction: done
  Verifying transaction: done
  Executing transaction: done
  #
  # To activate this environment, use
  #
  #     $ conda activate test_env4
  #
  # To deactivate an active environment, use
  #
  #     $ conda deactivate
```
  </p>
</details>

**Comment by xylar** [comment]
I think this might be a dask/numpy issue and probably unrelated to xarray: https://github.com/dask/dask/issues/4378

I'll close this but others can re-open if need be.
