### ISSUE TITLE
Documentation fails to build

### ISSUE THREAD

**Issue by yohai** [pydata/xarray#2743]
I'm trying to build the doc and it fails. I have a fresh miniconda install with a test environment created as instructed in the docs (i.e. `conda env create -f ci/requirements-py36.yml` followed by `conda install -c conda-forge sphinx sphinx_rtd_theme sphinx-gallery numpydoc`).

#### Code Sample, a copy-pastable example if possible

```shell
make clean
make html
```
#### Problem description
It generates the following error:

```
Exception occurred:
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/IPython/sphinxext/ipython_directive.py", line 567, in process_input
    raise RuntimeError('Non Expected exception in `{}` line {}'.format(filename, lineno))
RuntimeError: Non Expected exception in `/Users/yohai/Dropbox/Coding/xarray/doc/io.rst` line 376
The full traceback has been saved in /var/folders/mj/g9tnmysj6zld_3dg6hm9tkk00000gn/T/sphinx-err-8q55qmxi.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

The problem seems to be in `doc/io.rst`. When I delete all lines upto [line 367](https://github.com/pydata/xarray/blame/master/doc/io.rst#L367) it builds well
The content of the traceback logfile:
<details>
```
# Sphinx version: 1.8.4
# Python version: 3.6.7 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   reading sources... [ 97%] indexing
#   
#   reading sources... [ 97%] installing
#   
#   reading sources... [ 97%] internals
#   
#   reading sources... [ 97%] interpolation
#   
#   reading sources... [ 98%] io
#   
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.4) from /Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from /Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.8.4) from /Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (1.8.4) from /Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.intersphinx (1.8.4) from /Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.extlinks (1.8.4) from /Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/ext/extlinks.py
#   numpydoc (0.8.0) from /Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/numpydoc/__init__.py
#   IPython.sphinxext.ipython_directive (unknown version) from /Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/IPython/sphinxext/ipython_directive.py
#   IPython.sphinxext.ipython_console_highlighting (unknown version) from /Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/IPython/sphinxext/ipython_console_highlighting.py
#   sphinx_gallery.gen_gallery (0.2.0) from /Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx_gallery/gen_gallery.py
Traceback (most recent call last):
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/sphinx/parsers.py", line 88, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/IPython/sphinxext/ipython_directive.py", line 1005, in run
    rows, figure = self.shell.process_block(block)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/IPython/sphinxext/ipython_directive.py", line 711, in process_block
    self.process_input(data, input_prompt, lineno)
  File "/Users/yohai/miniconda3/envs/test_env/lib/python3.6/site-packages/IPython/sphinxext/ipython_directive.py", line 567, in process_input
    raise RuntimeError('Non Expected exception in `{}` line {}'.format(filename, lineno))
RuntimeError: Non Expected exception in `/Users/yohai/Dropbox/Coding/xarray/doc/io.rst` line 376
```
</details>

#### Output of ``xr.show_versions()``

<details>
xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:37:09)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.2

xarray: 0.11.1+49.g27cf53f2
pandas: 0.24.1
numpy: 1.15.4
scipy: 1.2.0
netCDF4: 1.4.2
pydap: installed
h5netcdf: 0.6.2
h5py: 2.9.0
Nio: None
zarr: 2.2.0
cftime: 1.0.3.4
PseudonetCDF: None
rasterio: 1.0.15
cfgrib: 0.9.5.5
iris: None
bottleneck: 1.2.1
cyordereddict: None
dask: 1.1.1
distributed: 1.25.3
matplotlib: 3.0.2
cartopy: 0.17.0
seaborn: 0.9.0
setuptools: 40.7.1
pip: 19.0.1
conda: None
pytest: 4.2.0
IPython: 7.2.0
sphinx: 1.8.4
</details>

**Comment by shoyer** [comment]
Can you try installing the environment that we use for building the docs: `conda env create -n test_env --file doc/environment.yml`?

**Comment by yohai** [comment]
Works fine. Thanks. It does suggest there's a problem though, no? Why are there two separate environment specs?

**Comment by yohai** [comment]
OK I think I know what's going on. On a fresh environment it works, but then I installed `ipykernel` so that I could fiddle around on `Jupyter` and after that it doesn't work anymore. I don't know if it's of interest to try to fix this or not, I'll let you decide. 

Here are the package changes when installing `ipykernel`

```bash
(test_env)$ conda install ipykernel
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /Users/yohai/miniconda3/envs/test_env

  added / updated specs:
    - ipykernel


The following NEW packages will be INSTALLED:

  ipykernel          conda-forge/osx-64::ipykernel-5.1.0-py37h24bf2e0_1002
  jupyter_client     conda-forge/noarch::jupyter_client-5.2.4-py_1
  jupyter_core       conda-forge/noarch::jupyter_core-4.4.0-py_0
  libsodium          conda-forge/osx-64::libsodium-1.0.16-h1de35cc_1001
  pyzmq              conda-forge/osx-64::pyzmq-17.1.2-py37h111632d_1001
  zeromq             conda-forge/osx-64::zeromq-4.2.5-h0a44026_1006

The following packages will be UPDATED:

  expat              conda-forge::expat-2.2.5-h0a44026_1002 --> pkgs/main::expat-2.2.6-h0a44026_0
  libpq               conda-forge::libpq-10.6-hbe1e24e_1000 --> pkgs/main::libpq-11.1-h051b688_0
  openssl                              1.0.2p-h1de35cc_1002 --> 1.1.1a-h1de35cc_1000
  pcre                 conda-forge::pcre-8.41-h0a44026_1003 --> pkgs/main::pcre-8.42-h378b8a2_0
  postgresql         conda-forge::postgresql-10.6-ha1bbaa7~ --> pkgs/main::postgresql-11.1-h051b688_0
  python             conda-forge::python-3.7.1-h145921a_10~ --> pkgs/main::python-3.7.2-haf84260_0

The following packages will be SUPERSEDED by a higher-priority channel:

  cryptography       conda-forge::cryptography-2.5-py37hdb~ --> pkgs/main::cryptography-2.4.2-py37ha12b0ac_0
  curl               conda-forge::curl-7.63.0-heae2a1f_1000 --> pkgs/main::curl-7.63.0-ha441bb4_1000
  krb5               conda-forge::krb5-1.16.3-h24a3359_1000 --> pkgs/main::krb5-1.16.1-hddcf347_7
  libcurl            conda-forge::libcurl-7.63.0-h76de61e_~ --> pkgs/main::libcurl-7.63.0-h051b688_1000
  libgdal            conda-forge::libgdal-2.4.0-h89caebc_1~ --> pkgs/main::libgdal-2.3.3-h0950a36_0

The following packages will be DOWNGRADED:

  libssh2                               1.8.0-hf30b1f0_1003 --> 1.8.0-1
  rasterio                            1.0.13-py37h3683dd5_1 --> 1.0.13-py37h54a03ab_0
```

**Comment by shoyer** [comment]
Conda forge recently had a painful process where they rebuilt every package against new compiler versions. It's possible `ipykernel` may not have been rebuilt yet, which is why conda is trying to install an old rasterio build (which crashes).

**Comment by yohai** [comment]
OK. So no point in fixing this. Thanks.
