### ISSUE TITLE
ClassVar from typing is supported python version >=3.5.3

### ISSUE THREAD

**Issue by TAlonglong** [pydata/xarray#2866]
```
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xarray.ufuncs as xu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/software/pytroll/virtual-env-test/pytroll/lib/python3.5/site-packages/xarray/__init__.py", line 26, in <module>
    from .coding.cftime_offsets import cftime_range
  File "/software/pytroll/virtual-env-test/pytroll/lib/python3.5/site-packages/xarray/coding/cftime_offsets.py", line 46, in <module>
    from typing import ClassVar, Optional
ImportError: cannot import name 'ClassVar'
>>> 
```

Looks like the `setup.py` https://github.com/pydata/xarray/blob/master/setup.py#L25 python version 3.5.2 should be supported.

**Comment by TAlonglong** [comment]
https://docs.python.org/3/library/typing.html#typing.ClassVar

**Comment by shoyer** [comment]
This was fixed by https://github.com/pydata/xarray/pull/2831

Yes, I need to issue a new release...
