### ISSUE TITLE
Error in to_netcdf()

### ISSUE THREAD

**Issue by tlogan2000** [pydata/xarray#3080]
#### MCVE Code Sample

In order for the maintainers to efficiently understand and prioritize issues, we ask you post a "Minimal, Complete and Verifiable Example" (MCVE): http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
import xarray as xr
print(xr.__version__)

url = 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/cccs_portal/indices/Final/BCCAQv2/tg_mean/YS/rcp26/simulations/BCCAQv2+ANUSPLIN300_bcc-csm1-1_historical+rcp26_r1i1p1_1950-2100_tg_mean_YS.nc'
ds = xr.open_dataset(url, chunks={'time':50})
dsSel = ds.sel(lon= -80, lat= 50, method='nearest')
outnc = 'tmp.nc'
dsSel.to_netcdf(outnc)

```

#### Problem Description
This may be related to #2850 but I am unable to save to netcdf after performing a simple ```sel``` for certain .nc files (example file available via opendap link in the code) . Gives following error :
```Traceback (most recent call last):
  File "/home/travis/.conda/envs/Xarray/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-492c82b08e81>", line 8, in <module>
    dsSel.to_netcdf(outnc)
  File "/home/travis/.conda/envs/Xarray/lib/python3.6/site-packages/xarray/core/dataset.py", line 1365, in to_netcdf
    compute=compute)
  File "/home/travis/.conda/envs/Xarray/lib/python3.6/site-packages/xarray/backends/api.py", line 886, in to_netcdf
    unlimited_dims=unlimited_dims)
  File "/home/travis/.conda/envs/Xarray/lib/python3.6/site-packages/xarray/backends/api.py", line 929, in dump_to_store
    unlimited_dims=unlimited_dims)
  File "/home/travis/.conda/envs/Xarray/lib/python3.6/site-packages/xarray/backends/common.py", line 269, in store
    self.set_attributes(attributes)
  File "/home/travis/.conda/envs/Xarray/lib/python3.6/site-packages/xarray/backends/common.py", line 285, in set_attributes
    self.set_attribute(k, v)
  File "/home/travis/.conda/envs/Xarray/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 426, in set_attribute
    _set_nc_attribute(self.ds, key, value)
  File "/home/travis/.conda/envs/Xarray/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 302, in _set_nc_attribute
    obj.setncattr(key, value)
  File "netCDF4/_netCDF4.pyx", line 2607, in netCDF4._netCDF4.Dataset.setncattr
  File "netCDF4/_netCDF4.pyx", line 1467, in netCDF4._netCDF4._set_att
  File "netCDF4/_netCDF4.pyx", line 1733, in netCDF4._netCDF4._ensure_nc_success
AttributeError: NetCDF: String match to name in use
```

#### Expected Output
saved selection to .nc
#### Output of ``xr.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 4.15.0-54-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_CA.UTF-8
LOCALE: en_CA.UTF-8
libhdf5: 1.10.2
libnetcdf: 4.6.1
xarray: 0.12.2
pandas: 0.23.3
numpy: 1.15.4
scipy: 1.2.0
netCDF4: 1.4.0
pydap: None
h5netcdf: 0.6.1
h5py: 2.8.0
Nio: None
zarr: None
cftime: 1.0.3.4
nc_time_axis: None
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.2.1
dask: 1.0.0
distributed: 1.25.2
matplotlib: 3.0.1
cartopy: None
seaborn: None
numbagg: None
setuptools: 39.2.0
pip: 19.1.1
conda: None
pytest: 3.8.1
IPython: 6.5.0
sphinx: 2.1.2
</details>

**Comment by andrew-c-ross** [comment]
I think you're right, this is nearly the same issue as #2850. Your dataset has an attribute named _NCProperties which is one of the [hidden/forbidden attributes](https://www.unidata.ucar.edu/software/netcdf/docs/file_format_specifications.html#atts_spec). 

If I remove the attribute:
`del dsSel.attrs['_NCProperties']`

`dsSel.to_netcdf(outnc)` then works for me with no errors.

You can also delete the attribute on `ds` instead and subsequent selections should also work. 

As an aside, if I run
`ncdump -h https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/cccs_portal/indices/Final/BCCAQv2/tg_mean/YS/rcp26/simulations/BCCAQv2+ANUSPLIN300_bcc-csm1-1_historical+rcp26_r1i1p1_1950-2100_tg_mean_YS.nc `
"_NCProperties" doesn't show up in the attributes, but I assume this is because ncdump hides it and not because it gets added by xarray or netcdf4. If that's not the case it could be a bug in xarray or netcdf4.

**Comment by kmuehlbauer** [comment]
Not sure if netcdf4-python has improved their error message since creation of this issue. But h5netcdf is raising a bit more meaningful error:

"cannot write attribute with reserved name _NCProperties"

As this is implementation detail of netcdf4-python, I'd favour an upstream fix of the error message (if not yet done).

Please reopen if you think otherwise.
