### ISSUE TITLE
scipy skewnorm function doesnt work with xarray rolling window?

### ISSUE THREAD

**Issue by mada0007** [pydata/xarray#3184]
#### MCVE Code Sample

```python
loc,scale,shape = da.rolling(time=59).reduce(scipy.stats.skewnorm)


```

#### Expected Output

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/mada0007/anaconda3/envs/modes/lib/python3.7/site-packages/xarray/core/rolling.py", line 217, in reduce
    result = windows.reduce(func, dim=rolling_dim, **kwargs)
  File "/Users/mada0007/anaconda3/envs/modes/lib/python3.7/site-packages/xarray/core/dataarray.py", line 1636, in reduce
    var = self.variable.reduce(func, dim, axis, keep_attrs, **kwargs)
  File "/Users/mada0007/anaconda3/envs/modes/lib/python3.7/site-packages/xarray/core/variable.py", line 1371, in reduce
    data = func(input_data, axis=axis, **kwargs)
  File "/Users/mada0007/anaconda3/envs/modes/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 770, in __call__
    return self.freeze(*args, **kwds)
  File "/Users/mada0007/anaconda3/envs/modes/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 767, in freeze
    return rv_frozen(self, *args, **kwds)
  File "/Users/mada0007/anaconda3/envs/modes/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 435, in __init__
    shapes, _, _ = self.dist._parse_args(*args, **kwds)
TypeError: _parse_args() got an unexpected keyword argument 'axis'

#### Output of ``ommit: None
python: 3.7.2 (default, Dec 29 2018, 00:00:04) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: en_AU.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.2
xarray: 0.12.1
pandas: 0.24.2
numpy: 1.15.4
scipy: 1.2.1
netCDF4: 1.5.1.2
pydap: installed
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.0.3.4
nc_time_axis: None
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 1.2.2
distributed: 1.28.1
matplotlib: 3.0.3
cartopy: 0.17.0
seaborn: 0.9.0
setuptools: 40.8.0
pip: 19.0.3
conda: None
pytest: None
IPython: None
sphinx: None``

How can I please make this code work?

**Comment by max-sixty** [comment]
Unless anyone quickly knows the answer, @mada0007 please could you post a repro example, as explained in the issue template?

**Comment by dcherian** [comment]
I suspect it's that `reduce` expects functions to accept an `axis` kwarg. If you write a wrapper that looks like

```
def wrapper(arr, axis=None):
    return scipy....(arr)
```
it may work.
