### ISSUE TITLE
OSError: [Errno -101] NetCDF: HDF error

### ISSUE THREAD

**Issue by jinlx** [pydata/xarray#3327]
Hi,
I am trying to use xarray to read netCDF4 data. However, I met error below. Any suggestions on it?
```python
# Your code here
#!/usr/bin/env python

# Imports
import xarray as xr    
import numpy as np

# Read a restart file into an xarray Dataset object
ds = xr.open_dataset("glade/u/home/lixujin/GEOS-CHEM/rundirs/geosfp_4x5_tropchem/GEOSChem.Restart.20170801_0000z.nc4")
 
# Print the contents of the DataSet
#print(ds)
```

Traceback
```
Traceback (most recent call last):
  File "test_area.py", line 8, in <module>
    ds = xr.open_dataset("GEOSChem.Restart.20170801_0000z.nc4")
  File "/glade/u/home/lixujin/anaconda3/envs/gcpy/lib/python3.6/site-packages/xarray/backends/api.py", line 321, in open_dataset
    filename_or_obj, group=group, lock=lock, **backend_kwargs)
  File "/glade/u/home/lixujin/anaconda3/envs/gcpy/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 355, in open
    return cls(manager, lock=lock, autoclose=autoclose)
  File "/glade/u/home/lixujin/anaconda3/envs/gcpy/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 314, in __init__
    self.format = self.ds.data_model
  File "/glade/u/home/lixujin/anaconda3/envs/gcpy/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 359, in ds
    return self._manager.acquire().value
  File "/glade/u/home/lixujin/anaconda3/envs/gcpy/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 172, in acquire
    file = self._opener(*self._args, **kwargs)
  File "/glade/u/home/lixujin/anaconda3/envs/gcpy/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 247, in _open_netcdf4_group
    ds = nc4.Dataset(filename, mode=mode, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 2135, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1752, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/glade/u/home/lixujin/GEOS-CHEM/rundirs/geosfp_4x5_tropchem/GEOSChem.Restart.20170801_0000z.nc4'
```

**Comment by dcherian** [comment]
Is the file corrupt? Does `ncdump -h` work?

**Comment by jinlx** [comment]
> Is the file corrupt? Does `ncdump -h` work?

You are right. The data is corrupted. Thanks for pointing out.

**Comment by dcherian** [comment]
I think we should catch this error and reraise suggesting that the file may be corrupt
