### ISSUE TITLE
Cannot write array larger than 4GB with SciPy netCDF backend

### ISSUE THREAD

**Issue by angelolab** [pydata/xarray#3416]
#### MCVE Code Sample

```python
# Your code here
import numpy as np
import xarray as xr

random_vals = np.random.randint(0, 10, 180*1024*1024*5)
test_array = random_vals.reshape((180, 1024, 1024, 5))
test_xr = xr.DataArray(test_array, coords=[range(test_array.shape[0]), range(test_array.shape[1]), range(test_array.shape[2]), range(test_array.shape[3])],
                       dims=["Image", "Rows", "Cols", "Channels"])

test_xr.to_netcdf("test_xr.nc", format="NETCDF3_64BIT")

```

#### Expected Output
This should either give an error that the requested array is too big to save, or should successfully save it. 

#### Problem Description

However, what instead happens is a long a stack trace that gives an OS error , which is confusing to debug. Reducing the dimensionality of the above data by a factor of 10 removes this error, demonstrating that it is a size issue. 

Traceback (most recent call last):
  File "/Users/noahgreenwald/Documents/Grad_School/Lab/Segmentation_Project/code/segmentation/env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-6ad9f8a3fa66>", line 1, in <module>
    test_xr.to_netcdf("test_xr.nc", format="NETCDF3_64BIT")
  File "/Users/noahgreenwald/Documents/Grad_School/Lab/Segmentation_Project/code/segmentation/env/lib/python3.6/site-packages/xarray/core/dataarray.py", line 1791, in to_netcdf
    return dataset.to_netcdf(*args, **kwargs)
  File "/Users/noahgreenwald/Documents/Grad_School/Lab/Segmentation_Project/code/segmentation/env/lib/python3.6/site-packages/xarray/core/dataset.py", line 1323, in to_netcdf
    compute=compute)
  File "/Users/noahgreenwald/Documents/Grad_School/Lab/Segmentation_Project/code/segmentation/env/lib/python3.6/site-packages/xarray/backends/api.py", line 822, in to_netcdf
    store.close()
  File "/Users/noahgreenwald/Documents/Grad_School/Lab/Segmentation_Project/code/segmentation/env/lib/python3.6/site-packages/xarray/backends/scipy_.py", line 226, in close
    self._manager.close()
  File "/Users/noahgreenwald/Documents/Grad_School/Lab/Segmentation_Project/code/segmentation/env/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 188, in close
    file.close()
  File "/Users/noahgreenwald/Documents/Grad_School/Lab/Segmentation_Project/code/segmentation/env/lib/python3.6/site-packages/scipy/io/netcdf.py", line 299, in close
    self.flush()
  File "/Users/noahgreenwald/Documents/Grad_School/Lab/Segmentation_Project/code/segmentation/env/lib/python3.6/site-packages/scipy/io/netcdf.py", line 409, in flush
    self._write()
  File "/Users/noahgreenwald/Documents/Grad_School/Lab/Segmentation_Project/code/segmentation/env/lib/python3.6/site-packages/scipy/io/netcdf.py", line 421, in _write
    self._write_var_array()
  File "/Users/noahgreenwald/Documents/Grad_School/Lab/Segmentation_Project/code/segmentation/env/lib/python3.6/site-packages/scipy/io/netcdf.py", line 477, in _write_var_array
    self._write_var_data(name)
  File "/Users/noahgreenwald/Documents/Grad_School/Lab/Segmentation_Project/code/segmentation/env/lib/python3.6/site-packages/scipy/io/netcdf.py", line 525, in _write_var_data
    self.fp.write(var.data.tostring())
OSError: [Errno 22] Invalid argument

#### Output of ``xr.show_versions()``
<details>
# Paste the output here xr.show_versions() here
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
python-bits: 64
OS: Darwin
OS-release: 18.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: en_US.UTF-8
libhdf5: None
libnetcdf: None
xarray: 0.12.1
pandas: 0.24.2
numpy: 1.16.3
scipy: 1.2.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudonetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 2.2.2
cartopy: None
seaborn: None
setuptools: 39.0.1
pip: 9.0.3
conda: None
pytest: None
IPython: 7.8.0
sphinx: None

</details>

**Comment by max-sixty** [comment]
Thanks for the issue @angelolab 

Are you sure this is an xarray error? It looks like the error is being raised from scipy

**Comment by ngreenwald** [comment]
Yes, you're right, seems like the actual IO is happening within scipy. Do you have any suggestions for how I might troubleshoot this further? Could I make a similar example that uses only the scipy netcdf functionality somehow to drill down into where the memory error is coming from?

**Comment by shoyer** [comment]
This array is 7.5 GB in size, which unfortunately is too big to be stored as a single record in the netCDF3 file format, even the 64-bit version: 
https://www.unidata.ucar.edu/software/netcdf/docs/file_format_specifications.html#offset_format_spec

We could potentially support writing these variables to disk with scipy, but it would require refactoring xarray's scipy netCDF backend to write record variables (with indeterminate size), which we currently don't use.

In the meanwhile, the best work-around is to use the netCDF4 file format, either via the netCDF4 Python package or h5netcdf.

**Comment by shoyer** [comment]
SciPy's netCDF module has an additional limitation that would likely be limiting for writing large files: it currently writes netCDF files by loading the entire file into memory at once. Ideally it would support incrementally writing data.

**Comment by crusaderky** [comment]
The error message is clearly improvable, however this ticket belongs to the scipy board. @angeloab please reopen it there. All ok with closing this?

**Comment by angelolab** [comment]
Got it, thanks everyone. I'll open this issue there. We'll try and work on getting our NetCDF4 compatibility issues addressed to avoid this space issue, as we are working with large imaging datasets.
