### ISSUE TITLE
AttributeError: NetCDF: Not a valid ID 

### ISSUE THREAD

**Issue by erjsarrav** [pydata/xarray#3613]
I have some code that  plots netCDF data with Python
https://joehamman.com/2013/10/12/plotting-netCDF-data-with-Python/?fbclid=IwAR3OGyCRHupg8jhbrymwlFXyswsU0dKRF6DweU0sjDv5JsVOgc4Vo49_tL8

When i run the code I have an error

``` python
import os
os.environ['PROJ_LIB'] = r'C:\Users\erjigitov\Anaconda2\pkgs\proj4-5.2.0-ha925a31_1\Library\share'
import  netCDF4 as nc
import numpy as np

data = nc.Dataset('C:/Users/erjigitov/Downloads/Temperature/t2m_2001.nc')

lons = data.variables['longitude']
lats = data.variables['latitude']
temp = data.variables['t2m']

temp_units=data.variables['t2m'].units

data.close()


import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap

# Get some parameters for the Stereographic Projection
lon_0 = lons.mean()
lat_0 = lats.mean()

m = Basemap(width=5000000,height=3500000,
            resolution='l',projection='stere',\
            lat_ts=40,lat_0=lat_0,lon_0=lon_0)

# Because our lon and lat variables are 1D,
# use meshgrid to create 2D arrays
# Not necessary if coordinates are already in 2D arrays.
lon, lat = np.meshgrid(lons, lats)
xi, yi = m(lon, lat)

# Plot Data
cs = m.pcolor(xi,yi,np.squeeze(temp))

# Add Grid Lines
m.drawparallels(np.arange(-80., 81., 10.), labels=[1,0,0,0], fontsize=10)
m.drawmeridians(np.arange(-180., 181., 10.), labels=[0,0,0,1], fontsize=10)

# Add Coastlines, States, and Country Boundaries
m.drawcoastlines()
m.drawstates()
m.drawcountries()

# Add Colorbar
cbar = m.colorbar(cs, location='bottom', pad="10%")
cbar.set_label(temp_units)

# Add Title
plt.title('DJF Maximum Temperature')

plt.show()
```

```
 runfile('C:/Users/erjigitov/Documents/Research/Data/Example_visual/plots.py', wdir='C:/Users/erjigitov/Documents/Research/Data/Example_visual')
Traceback (most recent call last):

  File "<ipython-input-34-3b399d45b1cd>", line 1, in <module>
    runfile('C:/Users/erjigitov/Documents/Research/Data/Example_visual/plots.py', wdir='C:/Users/erjigitov/Documents/Research/Data/Example_visual')

  File "C:\Users\erjigitov\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\erjigitov\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 95, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/erjigitov/Documents/Research/Data/Example_visual/plots.py", line 27, in <module>
    lon_0 = lons.mean()

  File "netCDF4\_netCDF4.pyx", line 4071, in netCDF4._netCDF4.Variable.__getattr__

  File "netCDF4\_netCDF4.pyx", line 3882, in netCDF4._netCDF4.Variable.getncattr

  File "netCDF4\_netCDF4.pyx", line 1289, in netCDF4._netCDF4._get_att

  File "netCDF4\_netCDF4.pyx", line 1754, in netCDF4._netCDF4._ensure_nc_success

AttributeError: NetCDF: Not a valid ID
```

**Comment by TomNicholas** [comment]
Hi @erjsarrav, it's a bit hard to read the formatting of your post (if you're having trouble with markdown, [here's a useful guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)), but it doesn't appear to me that your issue is with xarray? You aren't importing xarray, just netcdf (which xarray wraps), and the blog post you linked to is from before the initial release of xarray.

Whatever is causing your issue, a ["minimum, complete, verifiable example"](https://xarray.pydata.org/en/latest/contributing.html#bug-reports-and-enhancement-requests) which reproduces your bug will help people to solve it. You might want to try posting on the issues page for [netcdf4-python](https://github.com/Unidata/netcdf4-python).
