### ISSUE TITLE
open_mfdataset - different behavior with dask.distributed.LocalCluster

### ISSUE THREAD

**Issue by eyou102** [pydata/xarray#3684]
Big fan of Xarray!  Not that familiar with submitting tickets like this, so my apologies for rule breaking.  Also, if this belongs over in the dask project, I can move there.

dask 2.6.0
numpy 1.17.3
xarray 0.14.1
netCDF4 1.5.3

I am attempting to use open_mfdataset on nc files I've generated through dask/xarray after initializing the dask LocalCluster.  I've found that I am able to compute successfully when I don't run the distributed cluster.  But if I do, I get a variety of issues.  I've got a synthetic data generating example here.  Running the soundspeed.compute() will sometimes succeed, and will sometimes cause worker restarts resulting in hdf errors and no return.

I was thinking it was something with serialization, i've seen other tickets with similar issues, but I don't see how it applies to my test case.

Example code:

```python
import numpy as np
import xarray as xr
import os
from dask.distributed import Client

cl = Client()
outpth = r'D:\dasktest\data_dir\EM2040\converted\test'
mint = 0
maxt = 1000

for i in range(100):
    times = np.arange(mint, maxt)
    beams = np.arange(250)
    sectors=['40107_0_260000', '40107_1_320000', '40107_2_290000']
    soundspeed = np.random.randn(1000,3,250)
    ds = xr.Dataset({'soundspeed': (('time','sectors','beams'), soundspeed)},
                    {'time': times, 'sectors': sectors, 'beams':beams},)
    ds.to_netcdf(os.path.join(outpth, 'test{}.nc'.format(i)), mode='w')
    mint = maxt
    maxt += 1000

fils = [os.path.join(outpth, x) for x in os.listdir(outpth) if os.path.splitext(x)[1] == '.nc']
tst = xr.open_mfdataset(fils, concat_dim='time', combine='nested')
tst.soundspeed.compute()
```

I've found that running this example with <10 files reduces the number of errors I'm getting dramatically.  I've tried this on different machines in different domain environments just to be sure. 
 I really just want to make sure I'm not making a silly mistake somewhere.  Appreciate the help.

My last run on actual data:

```python
>>> ra.soundspeed.compute()
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001F83F1E2360>, key=BasicIndexer((slice(None, None, None), slice(None, None, None)))))), (slice(0, 1719, None), slice(0, 3, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\dataarray.py", line 837, in compute
    return new.load(**kwargs)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\dataarray.py", line 811, in load
    ds = self._to_temp_dataset().load(**kwargs)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\dataset.py", line 649, in load
    evaluated_data = da.compute(*lazy_data.values(), **kwargs)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\dask\base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\distributed\client.py", line 2545, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\distributed\client.py", line 1845, in gather
    asynchronous=asynchronous,
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\distributed\client.py", line 762, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\distributed\utils.py", line 333, in sync
    raise exc.with_traceback(tb)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\distributed\utils.py", line 317, in f
    result[0] = yield future
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\distributed\client.py", line 1701, in _gather
    raise exception.with_traceback(traceback)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\dask\array\core.py", line 106, in getter
    c = np.asarray(c)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\indexing.py", line 481, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\indexing.py", line 643, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\indexing.py", line 547, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\backends\netCDF4_.py", line 72, in __getitem__
    key, self.shape, indexing.IndexingSupport.OUTER, self._getitem
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\indexing.py", line 827, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\backends\netCDF4_.py", line 83, in _getitem
    original_array = self.get_array(needs_lock=False)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\backends\netCDF4_.py", line 62, in get_array
    ds = self.datastore._acquire(needs_lock)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\backends\netCDF4_.py", line 360, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "C:\PydroXL_19\envs\dasktest\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\backends\file_manager.py", line 186, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\backends\file_manager.py", line 204, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "netCDF4\_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4\_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'D:\\dasktest\\data_dir\\EM2040\\converted\\rangeangle_20.nc'
```

My last run on the synthetic data set generated above:

```python
>>> tst.soundspeed.compute()
distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FC8AA20>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FCB82D0>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FCB8240>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FCB81F8>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FCB81B0>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FCB8360>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FCB83A8>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FCB8510>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FCB8750>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FCB8990>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FCB8BD0>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FCB8E10>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FC9D090>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FC9D2D0>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FC9D510>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FC9D750>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FC9DC18>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FC9DBD0>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FC9DCA8>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.netCDF4_.NetCDF4ArrayWrapper object at 0x000001BB5FC9DD38>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None)))))), (slice(0, 1000, None), slice(0, 3, None), slice(0, 250, None)))
kwargs:    {}
Exception: OSError(-101, 'NetCDF: HDF error')

  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\dataarray.py", line 837, in compute
    return new.load(**kwargs)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\dataarray.py", line 811, in load
    ds = self._to_temp_dataset().load(**kwargs)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\dataset.py", line 649, in load
    evaluated_data = da.compute(*lazy_data.values(), **kwargs)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\dask\base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\distributed\client.py", line 2545, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\distributed\client.py", line 1845, in gather
    asynchronous=asynchronous,
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\distributed\client.py", line 762, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\distributed\utils.py", line 333, in sync
    raise exc.with_traceback(tb)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\distributed\utils.py", line 317, in f
    result[0] = yield future
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\distributed\client.py", line 1701, in _gather
    raise exception.with_traceback(traceback)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\dask\array\core.py", line 106, in getter
    c = np.asarray(c)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\indexing.py", line 481, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\indexing.py", line 643, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\indexing.py", line 547, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\backends\netCDF4_.py", line 72, in __getitem__
    key, self.shape, indexing.IndexingSupport.OUTER, self._getitem
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\core\indexing.py", line 827, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\backends\netCDF4_.py", line 83, in _getitem
    original_array = self.get_array(needs_lock=False)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\backends\netCDF4_.py", line 62, in get_array
    ds = self.datastore._acquire(needs_lock)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\backends\netCDF4_.py", line 360, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "C:\PydroXL_19\envs\dasktest\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\backends\file_manager.py", line 186, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "C:\PydroXL_19\envs\dasktest\lib\site-packages\xarray\backends\file_manager.py", line 204, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "netCDF4\_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4\_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'D:\\dasktest\\data_dir\\EM2040\\converted\\test\\test4.nc'
```

**Comment by dcherian** [comment]
Does `xr.open_dataset('D:\\dasktest\\data_dir\\EM2040\\converted\\test\\test4.nc')` succeed?

**Comment by eyou102** [comment]
Each individual dataset opens successfully.

```python
>>> rslt = xr.open_dataset('D:\\dasktest\\data_dir\\EM2040\\converted\\test\\test4.nc')
>>> rslt
<xarray.Dataset>
Dimensions:     (beams: 250, sectors: 3, time: 1000)
Coordinates:
  * time        (time) int32 4000 4001 4002 4003 4004 ... 4996 4997 4998 4999
  * sectors     (sectors) object '40107_0_260000' ... '40107_2_290000'
  * beams       (beams) int32 0 1 2 3 4 5 6 7 ... 243 244 245 246 247 248 249
Data variables:
    soundspeed  (time, sectors, beams) float64 ...
>>> rslt.soundspeed.compute()
<xarray.DataArray 'soundspeed' (time: 1000, sectors: 3, beams: 250)>
array([[[ 1.44506928e+00, -1.51871078e+00, -3.23406027e+00, ...,
         -3.23209458e+00,  1.51651459e+00,  6.42639524e-01],
        [ 4.50549891e-01, -1.65891239e-01,  5.03328065e-01, ...,
          2.90603391e-02, -2.03399058e+00,  1.07384206e+00],
        [ 1.10102985e+00, -1.04792461e-01,  5.01006754e-01, ...,
         -6.85958163e-01, -6.03574819e-01,  3.82282291e-01]],

       [[ 1.84926818e-01,  9.15722054e-02, -1.21527347e+00, ...,
         -5.01625941e-01, -1.81885721e+00,  5.06066650e-01],
        [ 1.15374575e+00, -7.46658574e-01, -6.06853717e-01, ...,
         -1.91083642e+00,  1.82612868e-01, -1.75664446e+00],
        [ 5.15672540e-01, -6.77122781e-01, -1.52097291e+00, ...,
          1.20734955e+00, -4.89001010e-02,  1.62015033e+00]],

       [[ 1.21801104e-01, -4.34477805e-01, -1.34871232e+00, ...,
         -1.24627225e+00,  5.74698640e-01,  1.14271464e+00],
        [ 4.67490848e-01,  1.16150690e+00, -9.00648837e-01, ...,
         -1.48880232e+00, -1.41956820e-02, -8.61839051e-01],
        [-1.04143082e-01, -3.48620768e-01,  2.55312206e-01, ...,
          4.37058964e-01,  4.46445888e-01, -4.10217694e-01]],

       ...,

       [[ 1.61535162e+00,  1.74216005e-01, -3.09371662e+00, ...,
          1.26629794e+00, -9.18653539e-01, -2.37142082e+00],
        [-4.38608161e-02,  1.32472408e+00,  3.92494217e-01, ...,
         -1.03977601e+00, -1.87358228e+00,  1.71303085e+00],
        [ 1.40801908e-01, -4.85799815e-01, -4.28494910e-01, ...,
          5.88979031e-01, -3.16616983e-01, -4.03942439e-01]],

       [[-1.25221965e+00,  1.40617329e+00,  3.81911399e+00, ...,
         -1.41840680e+00, -8.81194686e-01,  2.24217335e+00],
        [-1.04704250e+00,  6.58982192e-01,  4.30801840e-01, ...,
          1.36966939e+00,  1.51575602e+00, -6.29969352e-01],
        [ 2.11058905e-01,  1.05525622e+00, -1.29686045e-01, ...,
         -1.33221475e+00,  1.74849717e-01,  2.15998814e+00]],

       [[-7.33979313e-02,  2.61711631e-01,  1.02465836e+00, ...,
          3.64389987e-01, -1.20189741e+00,  3.39280076e-01],
        [-4.03723405e-01, -2.21631345e+00, -9.94534629e-01, ...,
         -5.07692651e-01, -1.81561305e+00, -1.23491815e+00],
        [-6.36790749e-01, -8.00208607e-02,  5.46987721e-01, ...,
         -2.25807078e-03,  1.59638267e-01, -1.29816760e+00]]])
Coordinates:
  * time     (time) int32 4000 4001 4002 4003 4004 ... 4995 4996 4997 4998 4999
  * sectors  (sectors) object '40107_0_260000' '40107_1_320000' '40107_2_290000'
  * beams    (beams) int32 0 1 2 3 4 5 6 7 8 ... 242 243 244 245 246 247 248 249
>>> cl
<Client: 'tcp://127.0.0.1:59016' processes=4 threads=16, memory=34.27 GB>
```python

**Comment by singledoggy** [comment]
I encountered the same issue with different datasets. Individual datasets can be successfully opened.
