### ISSUE TITLE
NetCDF: HDF Error when using xr.open_mfdataset

### ISSUE THREAD

**Issue by nelerey** [pydata/xarray#4004]
**Please tell me if this issue belongs to dask or the netcdf4 packages instead.**

When trying to open a number of files in the same folder with open_mfdataset, I get the following lengthy error: 

```
testdatapaths = glob.glob('/Users/nelereyniers/data/hadukgrid/1km/1km_rainfall_day_v20190808/*' )
data = xr.open_mfdataset(testdatapaths)
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 4608382400:
  #000: H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1400 in H5F__open(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: H5Fint.c line 1700 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #003: H5Fsuper.c line 623 in H5F__super_read(): truncated file: eof = 298111576, sblock->base_addr = 0, stored_eof = 344601871
    major: File accessibilty
    minor: File has been truncated
Traceback (most recent call last):
  File "/anaconda3/envs/default-env/lib/python3.7/site-packages/xarray/backends/file_manager.py", line 198, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/anaconda3/envs/default-env/lib/python3.7/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/Users/nelereyniers/data/hadukgrid/1km/1km_rainfall_day_v20190808/rainfall_hadukgrid_uk_1km_day_19801001-19801031.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/default-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-43678543fd10>", line 1, in <module>
    data1km = xr.open_mfdataset(testdatapaths)
  File "/anaconda3/envs/default-env/lib/python3.7/site-packages/xarray/backends/api.py", line 908, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/anaconda3/envs/default-env/lib/python3.7/site-packages/xarray/backends/api.py", line 908, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
  File "/anaconda3/envs/default-env/lib/python3.7/site-packages/xarray/backends/api.py", line 502, in open_dataset
    filename_or_obj, group=group, lock=lock, **backend_kwargs
  File "/anaconda3/envs/default-env/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 358, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/anaconda3/envs/default-env/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 314, in __init__
    self.format = self.ds.data_model
  File "/anaconda3/envs/default-env/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 367, in ds
    return self._acquire()
  File "/anaconda3/envs/default-env/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 361, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/anaconda3/envs/default-env/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/anaconda3/envs/default-env/lib/python3.7/site-packages/xarray/backends/file_manager.py", line 186, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/anaconda3/envs/default-env/lib/python3.7/site-packages/xarray/backends/file_manager.py", line 204, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/Users/nelereyniers/data/hadukgrid/1km/1km_rainfall_day_v20190808/rainfall_hadukgrid_uk_1km_day_19801001-19801031.nc'
```

However, applying xr.open_dataset to one of the files I'm trying to open works fine:
```
In[4]: data_first = xr.open_dataset(testdatapaths[0])
In[5]: data_first
Out[5]: 
<xarray.Dataset>
Dimensions:                       (bnds: 2, projection_x_coordinate: 900, projection_y_coordinate: 1450, time: 30)
Coordinates:
  * time                          (time) datetime64[ns] 1980-06-01T12:00:00 ... 1980-06-30T12:00:00
  * projection_y_coordinate       (projection_y_coordinate) float64 -1.995e+05 ... 1.25e+06
  * projection_x_coordinate       (projection_x_coordinate) float64 -1.995e+05 ... 6.995e+05
    latitude                      (projection_y_coordinate, projection_x_coordinate) float64 ...
    longitude                     (projection_y_coordinate, projection_x_coordinate) float64 ...
Dimensions without coordinates: bnds
Data variables:
    rainfall                      (time, projection_y_coordinate, projection_x_coordinate) float64 ...
    transverse_mercator           int32 ...
    time_bnds                     (time, bnds) datetime64[ns] ...
    projection_y_coordinate_bnds  (projection_y_coordinate, bnds) float64 ...
    projection_x_coordinate_bnds  (projection_x_coordinate, bnds) float64 ...
Attributes:
    comment:        Daily resolution gridded climate observations
    creation_date:  2019-08-28T20:15:46
    frequency:      day
    institution:    Met Office
    references:     doi: 10.1002/joc.1161
    short_name:     daily_rainfall
    source:         HadUK-Grid_v1.0.1.0
    title:          Gridded surface climate observations data for the UK
    version:        v20190808
    Conventions:    CF-1.5
```

Am I applying open_mfdataset in the wrong way or is this a bug? In case it's a bug - is there a known workaround? issue #3684 also reported xr.open_dataset working fine while xr.open_mfdataset resulted in `OSError(-101, 'NetCDF: HDF error')`.

Thank you

**Versions:**
python: 3.7.6
dask & dask-core: 2.8.1
hdf5: 1.10.4
netcdf4: 1.5.3
numpy: 1.18.1
xarray: 0.15.0

**Comment by nelerey** [comment]
Turned out to be a problem with one of the other datasets in the folder
