### ISSUE TITLE
Scipy ImportError: cannot import name 'ClassVar'

### ISSUE THREAD

**Issue by niju1** [pydata/xarray#4105]
I am new to Python and I was running the code below in Linux (Python 3.6.6) and there was an import error. I tried importing class variable from typing, but it didn't work. Could you please help me out?

```python
##########################################################################
#                                         Importing Libraries
##########################################################################
from lasso.dyna import *
import numpy as np
import xlsxwriter
import scipy.stats
import typing

##########################################################################
#                                        Importing d3plot file
##########################################################################

d3plot = D3plot('/home/ballal/Simulation/95/95_15/33/d3plot')

##########################################################################
#                                     Importing element result data
##########################################################################

element_eff_strain = d3plot.arrays[ArrayType.element_shell_effective_plastic_strain]
element_shell_stress = d3plot.arrays[ArrayType.element_shell_normal_force]
element_shell_internalenergy = d3plot.arrays[ArrayType.element_shell_internal_energy]
element_shell_is_alive = d3plot.arrays[ArrayType.element_shell_is_alive]
element_shell_unknownvariable = d3plot.arrays[ArrayType.element_shell_unknown_variables]

##########################################################################
#                                       Taking mean value of x,y,z
##########################################################################
element_eff_strain = np.mean(element_eff_strain, axis=2)
element_shell_stress = np.mean(element_shell_stress, axis=2)
element_shell_unknownvariable = np.mean(element_shell_unknownvariable, axis=2)

from sklearn.preprocessing import StandardScaler

element_lab = [element_eff_strain, element_shell_stress, element_shell_internalenergy, element_shell_is_alive]
element = StandardScaler().fit_transform(element_lab)
print(element)



####Error
Traceback (most recent call last):
  File "/home/ballal/Skripte/PCA.py", line 33, in <module>
    from sklearn.preprocessing import StandardScaler
  File "/home/ballal/Skripte/venv/lib64/python3.6/site-packages/sklearn/__init__.py", line 76, in <module>
    from .base import clone
  File "/home/ballal/Skripte/venv/lib64/python3.6/site-packages/sklearn/base.py", line 16, in <module>
    from .utils import _IS_32BIT
  File "/home/ballal/Skripte/venv/lib64/python3.6/site-packages/sklearn/utils/__init__.py", line 17, in <module>
    from . import _joblib
  File "/home/ballal/Skripte/venv/lib64/python3.6/site-packages/sklearn/utils/_joblib.py", line 8, in <module>
    import joblib
  File "/home/ballal/Skripte/venv/lib64/python3.6/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/home/ballal/Skripte/venv/lib64/python3.6/site-packages/joblib/parallel.py", line 29, in <module>
    from .externals.cloudpickle import dumps, loads
  File "/home/ballal/Skripte/venv/lib64/python3.6/site-packages/joblib/externals/cloudpickle/__init__.py", line 7, in <module>
    from .cloudpickle import *
  File "/home/ballal/Skripte/venv/lib64/python3.6/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 77, in <module>
    from typing import ClassVar
ImportError: cannot import name 'ClassVar'

**Comment by keewis** [comment]
that's a question about `sklearn` (there's no `xarray` involved here). I think you should ask the `sklearn` maintainers: https://github.com/scikit-learn/scikit-learn
