### ISSUE TITLE
open_mfdataset with 100 ROMS files each 1.7 GB hangs forever

### ISSUE THREAD

**Issue by knutfrode** [pydata/xarray#4198]
I am fairly new to Xarray, but have used it to open/aggregate a series of netCDF4-files, as this is not supported by python-netCDF directly.

So I am opening a series of ROMS ocean model files, with command like
```
self.Dataset = xr.open_mfdataset('ROMS_files_0*.nc',
                        chunks={'ocean_time': 1}, concat_dim='ocean_time', combine='by_coords',
                        preprocess=drop_non_essential_vars_pop,
                        data_vars='minimal', coords='minimal')
```

This works fine for order of 10 files, but when using ~100 of files (each 1.7GB) it never completes. When interrupting this command after 12 hours, I get the following traceback (indicating a threading issue?):

```
^CTraceback (most recent call last):
  File "martini.py", line 12, in <module>
    r = Reader('/lustre/storeB/project/fou/hi/martini/results/3y-1/martini_800m_his_0*.nc')
  File "/home/knutfd/software/opendrift/opendrift/readers/reader_ROMS_native.py", line 94, in __init__
    self.Dataset = xr.open_mfdataset(filename,
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/xarray/backends/api.py", line 958, in open_mfdataset
    combined = combine_by_coords(
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/xarray/core/combine.py", line 695, in combine_by_coords
    concatenated = _combine_nd(
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/xarray/core/combine.py", line 197, in _combine_nd
    combined_ids = _combine_all_along_first_dim(
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/xarray/core/combine.py", line 225, in _combine_all_along_first_dim
    new_combined_ids[new_id] = _combine_1d(
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/xarray/core/combine.py", line 247, in _combine_1d
    combined = concat(
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/xarray/core/concat.py", line 135, in concat
    return f(objs, dim, data_vars, coords, compat, positions, fill_value, join)
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/xarray/core/concat.py", line 357, in _dataset_concat
    result_vars[var] = unique_variable(
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/xarray/core/merge.py", line 137, in unique_variable
    equals = getattr(out, compat)(var)
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/xarray/core/variable.py", line 1722, in no_conflicts
    return self.broadcast_equals(other, equiv=equiv)
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/xarray/core/variable.py", line 1703, in broadcast_equals
    return self.equals(other, equiv=equiv)
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/xarray/core/variable.py", line 1687, in equals
    self._data is other._data or equiv(self.data, other.data)
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/xarray/core/duck_array_ops.py", line 235, in array_notnull_equiv
    return bool(flag_array.all())
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/dask/array/core.py", line 1475, in __bool__
    return bool(self.compute())
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/dask/base.py", line 444, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/dask/threaded.py", line 76, in get
    results = get_async(
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/dask/local.py", line 475, in get_async
    key, res_info, failed = queue_get(queue)
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/site-packages/dask/local.py", line 133, in queue_get
    return q.get()
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/queue.py", line 170, in get
    self.not_empty.wait()
  File "/home/knutfd/miniconda3/envs/opendrift/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

```

Corresponding aggregation of same amount/size of netCDF3/CLASSIC-files with python-netCDF is orders of magnitude faster to open.

Xarray versions:
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00) 
[GCC 7.5.0]
python-bits: 64
OS: Linux
OS-release: 5.3.0-61-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.15.1
pandas: 1.0.5
numpy: 1.18.5
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.1.3
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2.20.0
distributed: 2.20.0
matplotlib: 3.2.1
cartopy: 0.18.0
seaborn: None
numbagg: None
setuptools: 47.1.1.post20200529
pip: 20.1.1
conda: None
pytest: 5.4.3
IPython: None
sphinx: None
```

**Comment by knutfrode** [comment]
After it took about 12 hours to open a dataset of 100 files, it takes 40 minutes to read an array of 10x10 values, something which normally should take a fraction of a second.

**Comment by keewis** [comment]
can you post more information about that array of 10x10 values, or ideally some sample code to create files containing that small array? That way I can try to reproduce this.

You could also try to profile your code to find out where most of the time is spent.

**Comment by knutfrode** [comment]
My code is only the two lines, one to open and one to read:
```
self.Dataset = xr.open_mfdataset('ROMS_files_0*.nc',
                        chunks={'ocean_time': 1}, concat_dim='ocean_time', combine='by_coords',
                        preprocess=drop_non_essential_vars_pop,
                        data_vars='minimal', coords='minimal')
```
and
```
data = self.Dataset.variables['u'][0, 0:10, 0:10][:]
```

The first line takes 12 hours, and the last line takes 40 minutes. With python-netcdf the former takes order of one minute, and the latter a fraction of a second. But python-netcdf can not aggregate netCDF4 files.

**Comment by dcherian** [comment]
I think you need `compat="override"` to skip a bunch of equality checking. 

Do you have a suggestion for making this clearer in the docstring?

**Comment by knutfrode** [comment]
Thank you, ```compat=`override'``` made a huge difference. The dataset opened in 15 minutes, and reading is much faster. 
It was not obvious from the docstring that this setting had such big impact. Perhaps it could simply be added something like ```This setting may have large implications for performance```
