### ISSUE TITLE
Incompatibility between h5py package and xarray Dataset.to_netcdf()

### ISSUE THREAD

**Issue by rrbuchholz** [pydata/xarray#4277]
**What happened**:
I am trying to load hdf5 data, do calculations and then write out to netCDF. I was finding the xarray Dataset.to_netcdf() wasn't working correctly, so I went back to a simple exercise to reproduce the error. The example from http://xarray.pydata.org/en/stable/io.html does not seem to work correctly when also loading h5py. I receive this error:

>Traceback (most recent call last):
>  File "/usr/local/lib/python3.6/site-packages/xarray/backends/api.py", line 1089, in to_netcdf
>    dataset, store, writer, encoding=encoding, unlimited_dims=unlimited_dims
>  File "/usr/local/lib/python3.6/site-packages/xarray/backends/api.py", line 1135, in dump_to_store
>    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
>  File "/usr/local/lib/python3.6/site-packages/xarray/backends/common.py", line 298, in store
>    variables, check_encoding_set, writer, unlimited_dims=unlimited_dims
>  File "/usr/local/lib/python3.6/site-packages/xarray/backends/common.py", line 339, in set_variables
>    writer.add(source, target)
>  File "/usr/local/lib/python3.6/site-packages/xarray/backends/common.py", line 188, in add
>    target[...] = source
>  File "/usr/local/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 51, in __setitem__
>    data[key] = value
>  File "netCDF4/_netCDF4.pyx", line 4950, in netCDF4._netCDF4.Variable.__setitem__
>  File "netCDF4/_netCDF4.pyx", line 5229, in netCDF4._netCDF4.Variable._put
>  File "netCDF4/_netCDF4.pyx", line 1887, in netCDF4._netCDF4._ensure_nc_success
>RuntimeError: NetCDF: HDF error

And the netCDF file looks incorrect. A filedump gives:

>Variable: f
>Type: file
>filename:	saved_on_disk
>path:	saved_on_disk.nc
>
>dimensions:
>    phony_dim_0	= 4
>    phony_dim_1	= 5
>
>variables:
>    Variable: x
>    Type: float
>    Total Size: 4 values
>                16 bytes
>    Number of Dimensions: 1
>    Dimensions and sizes:	[ 4 <phony_dim_0> ]
>    Coordinates:
>
>    Variable: y
>    Type: float
>    Total Size: 5 values
>                20 bytes
>    Number of Dimensions: 1
>    Dimensions and sizes:	[ 5 <phony_dim_1> ]
>    Coordinates:
>
>    Variable: foo
>    Type: double
>    Total Size: 20 values
>                160 bytes
>    Number of Dimensions: 2
>    Dimensions and sizes:	[ 4 <phony_dim_0> x 5 <phony_dim_1> ]
>    Coordinates:
>        Number of Attributes:        2
>            _FillValue	: 	 nan
>            coordinates	: 	z

**What you expected to happen**:  The example code below under "Minimal Complete Verifiable Example" does not work correctly. However if I comment out the "import h5py" line, it works without any traceback erros and the netCDF file seems to write correctly. A filedump after it has worked correctly:

>Variable: f
>Type: file
>filename:	saved_on_disk
>path:	saved_on_disk.nc
>
>dimensions:
>    x	= 4
>    y	= 5
>
>variables:
>    Variable: foo
>    Type: double
>    Total Size: 20 values
>                160 bytes
>    Number of Dimensions: 2
>    Dimensions and sizes:	[ 4 <x> x 5 <y> ]
>    Coordinates:
>                x: [ 0.. 0]
>                y: [ 0.. 0]
>        Number of Attributes:        2
>            _FillValue	: 	 nan
>            coordinates	: 	z
>
>    Variable: x
>    Type: int64
>    Total Size: 4 values
>                32 bytes
>    Number of Dimensions: 1
>    Dimensions and sizes:	[ 4 <x> ]
>    Coordinates:
>                x: [ 0.. 0]
>
>    Variable: y
>    Type: int64
>    Total Size: 5 values
>                40 bytes
>    Number of Dimensions: 1
>    Dimensions and sizes:	[ 5 <y> ]
>    Coordinates:
>                y: [ 0.. 0]
>        Number of Attributes:        2
>            units	: 	days since 2000-01-01 00:00:00
>            calendar	: 	proleptic_gregorian
>
>    Variable: z
>    Type: string
>    Total Size: 4 values
>                32 bytes
>    Number of Dimensions: 1
>    Dimensions and sizes:	[ 4 <x> ]
>    Coordinates:
>                x: [ 0.. 0]

Do I need to use a different method to load my hdf5 files without using h5py?

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
import numpy as np
import pandas as pd
import h5py
import xarray as xr

ds = xr.Dataset(
     {"foo": (("x", "y"), np.random.rand(4, 5))},
     coords={
         "x": [10, 20, 30, 40],
         "y": pd.date_range("2000-01-01", periods=5),
         "z": ("x", list("abcd")),
     },
 )
 
ds.to_netcdf("saved_on_disk.nc")
```

**Anything else we need to know?**:

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8 (default, Apr  2 2020, 13:34:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1127.13.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.4
libnetcdf: 4.6.3

xarray: 0.15.1
pandas: 1.0.5
numpy: 1.18.4
scipy: 1.4.1
netCDF4: 1.5.3
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: 1.1.3
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.2.1
cartopy: 0.18.0
seaborn: None
numbagg: None
setuptools: 49.1.0
pip: 9.0.3
conda: None
pytest: None
IPython: None
sphinx: None

</details>

**Comment by rrbuchholz** [comment]
I discovered if loading xarray and h5py, you also need to load netCDF4, then the problem resolves.

https://stackoverflow.com/questions/63142417/python-xarray-and-h5py-incompatibility
