### ISSUE TITLE
netCDF4 Resource unavailable error

### ISSUE THREAD

**Issue by karlwx** [pydata/xarray#4304]
I've been encountering the following error occasionally when running some rather heavy scripts. Sometimes the code will run fine (with the same data) and other times it will exit with this traceback:
```Error 11: Resource temporarily unavailable
Traceback (most recent call last):
  File "globalmodels.py", line 213, in <module>
    run()
  File "globalmodels.py", line 210, in run
    M.make_maps(time)
  File "globalmodels.py", line 50, in make_maps
    d = TIGGEParser(ds)
  File "/EWALL_TEST/reforecast/utils/parsers.py", line 248, in __init__
    field = ds.sel(level=lev)[var['name']].values * units(var['units'])
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/core/dataarray.py", line 558, in values
    return self.variable.values
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/core/variable.py", line 446, in values
    return _as_array_or_item(self._data)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/core/variable.py", line 249, in _as_array_or_item
    data = np.asarray(data)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/core/indexing.py", line 677, in __array__
    self._ensure_cached()
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/core/indexing.py", line 674, in _ensure_cached
    self.array = NumpyIndexingAdapter(np.asarray(self.array))
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/core/indexing.py", line 653, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/core/indexing.py", line 557, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/coding/variables.py", line 72, in __array__
    return self.func(self.array)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/coding/variables.py", line 218, in _scale_offset_decoding
    data = np.array(data, dtype=dtype, copy=True)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/coding/variables.py", line 72, in __array__
    return self.func(self.array)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/coding/variables.py", line 138, in _apply_mask
    data = np.asarray(data, dtype=dtype)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/core/indexing.py", line 557, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 72, in __getitem__
    return indexing.explicit_indexing_adapter(
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/core/indexing.py", line 837, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
  File "/home/meteo/kps5442/.conda/envs/ewall/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 85, in _getitem
    array = getitem(original_array, key)
  File "netCDF4/_netCDF4.pyx", line 4408, in netCDF4._netCDF4.Variable.__getitem__
  File "netCDF4/_netCDF4.pyx", line 5352, in netCDF4._netCDF4.Variable._get
  File "netCDF4/_netCDF4.pyx", line 1887, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: Resource temporarily unavailable
```
The error occurs when I try to parse some information out of the dataset - I'm selecting based on level and then variable, and pulling out the values. From the error traceback, it seems like the values are causing the problem. 

I'm not sure if it matters, but this seems to only be a problem when I'm using multiprocessing, when there could be a number of processes parsing different datasets at the same time. Sometimes, though, this isn't a problem at all, and the code runs as expected with no errors. 

I'm not sure if this error is because of bad data, or limited resources. That would inform how I try to catch errors and re-try. I'm hoping someone here can point me in the right direction.

**Comment by max-sixty** [comment]
Sorry this never got a response. I'll close since there's no MVCE, but feel free to reopen if there is one.
