### ISSUE TITLE
Plotting when Interval coordinate is timedelta-based

### ISSUE THREAD

**Issue by gerritholl** [pydata/xarray#4378]
**Is your feature request related to a problem? Please describe.**

The xarray plotting interface supports coordinates containing `pandas.Interval` iff those intervals contain numbers.  It fails when those intervals contain `pandas.Timedelta`:

```python
import numpy as np
import pandas as pd
import xarray as xr

da = xr.DataArray(
        np.arange(10),
        dims=("x",),
        coords={"x": [pd.Interval(i, i+1) for i in range(10)]})
da.plot()  # works

da = xr.DataArray(
        np.arange(10),
        dims=("x",),
        coords={"x": [pd.Interval(
            d-pd.Timestamp("2000-01-01"),
            d-pd.Timestamp("2000-01-01")+pd.Timedelta("1H"))
            for d in pd.date_range("2000-01-01", "2000-01-02", 10)]})
da.plot()  # fails
```

The latter fails with:

```
Traceback (most recent call last):
  File "mwe82.py", line 18, in <module>
    da.plot()  # fails
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/xarray/plot/plot.py", line 446, in __call__
    return plot(self._da, **kwargs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/xarray/plot/plot.py", line 200, in plot
    return plotfunc(darray, **kwargs)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/xarray/plot/plot.py", line 302, in line
    _ensure_plottable(xplt_val, yplt_val)
  File "/data/gholl/miniconda3/envs/py38/lib/python3.8/site-packages/xarray/plot/utils.py", line 551, in _ensure_plottable
    raise TypeError(
TypeError: Plotting requires coordinates to be numeric or dates of type np.datetime64, datetime.datetime, cftime.datetime or pd.Interval.
```

This error message is somewhat confusing, because the coordinates _are_ "dates of type (...) pd.Interval", but perhaps a timedelta is not considered a date.

**Describe the solution you'd like**

I would like that I can use the xarray plotting interface for any pandas.Interval coordinate, including `pandas.Timestamp` and `pandas.Timedelta`.  

**Describe alternatives you've considered**

I'll "manually" calculate the midpoints and use those as a timedelta coordinate instead.

**Additional context**

It seems that regular timedeltas aren't really supported either, although they don't cause an error message, they rather produce [incorrect results](https://stackoverflow.com/q/50717534).  There's probably a related issue somewhere, but I can't find it now.

**Comment by mathause** [comment]
Quickly looking at the code this error message seems to not be entirely correct. That should probably be along the lines of

```diff
TypeError: Plotting requires coordinates to be numeric or dates of type
np.datetime64, datetime.datetime, cftime.datetime
- or pd.Interval.
+ or pd.Interval containing one of these dtypes.
```
The `pd.Interval` are used to calculate their midpoints. Then the dtype of the midpoints is checked:

https://github.com/pydata/xarray/blob/9c85dd5f792805bea319f01f08ee51b83bde0f3b/xarray/plot/utils.py#L578

But indeed matplotlib does not seem to be able to directly plot `pd.Timedelta`s 


```python
x = [d-pd.Timestamp("2000-01-01") for d in pd.date_range("2000-01-01", "2000-01-02", 10)]
plt.plot(x, np.arange(10))
TypeError: ...
```
So I am not sure we should try to be clever here.
