### ISSUE TITLE
Calling pd.to_datetime on cftime variable

### ISSUE THREAD

**Issue by raybellwaves** [pydata/xarray#4598]
It would be nice to be able to convert cftime variables to pandas datetime to utilize the functionality there.

I understand this is an upstream issue as pandas probably isn't aware of cftime. However, i'm curious if a method could be added to cftime such as .to_dataframe().

I've found `pd.to_datetime(np.datetime64(date_cf))` is the best way to do this currently.

```
import xarray as xr
import numpy as np
import pandas as pd

date_str = '2020-01-01'
date_np = np.datetime64(date_str)
>>> date_np
numpy.datetime64('2020-01-01')
date_pd = pd.to_datetime(date_np)
>>> date_pd
Timestamp('2020-01-01 00:00:00')

date_cf = xr.cftime_range(start=date_str, periods=1)[0]
pd.to_datetime(date_cf)
>>> pd.to_datetime(date_cf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray/local/bin/anaconda3/envs/a/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 830, in to_datetime
    result = convert_listlike(np.array([arg]), format)[0]
  File "/home/ray/local/bin/anaconda3/envs/a/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 459, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/home/ray/local/bin/anaconda3/envs/a/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 2044, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 352, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 579, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 718, in pandas._libs.tslib.array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 552, in pandas._libs.tslib.array_to_datetime
TypeError: <class 'cftime._cftime.DatetimeGregorian'> is not convertible to datetime
```

**Comment by spencerkclark** [comment]
We do not have anything in xarray that works for `cftime` scalars currently, but we do have a `to_datetimeindex` method on `CFTimeIndex`:
```
In [1]: import xarray as xr

In [2]: times = xr.cftime_range("2000", periods=2)

In [3]: times.to_datetimeindex()
Out[3]: DatetimeIndex(['2000-01-01', '2000-01-02'], dtype='datetime64[ns]', freq=None)
```
Which functionality are you looking for in xarray that pandas `Timestamp` objects provide, but `cftime` objects do not?

**Comment by raybellwaves** [comment]
> Which functionality are you looking for in xarray that pandas Timestamp objects provide, but cftime objects do not?

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.tz_localize.html

For a bit more reference. I'm working with HyCOM data and want to keep track of 'local time'.

```
ds = xr.open_dataset('https://tds.hycom.org/thredds/dodsC/GLBy0.08/latest', decode_times=False)
reference_date = ds.time.attrs['units'][12:25]
ds['time'] = xr.cftime_range(start=reference_date, periods=len(ds.time), freq='3H')
```

**Comment by spencerkclark** [comment]
I see, yeah, timezones with `cftime` are tricky.  Why are you using `cftime_range` to populate the time variable though in this case?  Why not `pandas.date_range`?  

The problematic variable in this dataset is `"tau"`.  If we drop that variable the dates are automatically decoded to pandas-compatible times (perhaps that's not an option for you though):
```
In [1]: import xarray as xr

In [2]: xr.open_dataset('https://tds.hycom.org/thredds/dodsC/GLBy0.08/latest', drop_variables=["tau"])
Out[2]:
<xarray.Dataset>
Dimensions:            (depth: 40, lat: 4251, lon: 4500, time: 101)
Coordinates:
  * lat                (lat) float64 -80.0 -79.96 -79.92 ... 89.92 89.96 90.0
  * lon                (lon) float64 0.0 0.07996 0.16 0.24 ... 359.8 359.8 359.9
  * depth              (depth) float64 0.0 2.0 4.0 6.0 ... 3e+03 4e+03 5e+03
  * time               (time) datetime64[ns] 2020-11-16T12:00:00 ... 2020-11-29
    time_run           (time) datetime64[ns] ...
Data variables:
    time_offset        (time) datetime64[ns] ...
    surf_el            (time, lat, lon) float32 ...
    water_u            (time, depth, lat, lon) float32 ...
    water_u_bottom     (time, lat, lon) float32 ...
    water_v            (time, depth, lat, lon) float32 ...
    water_v_bottom     (time, lat, lon) float32 ...
    water_temp         (time, depth, lat, lon) float32 ...
    water_temp_bottom  (time, lat, lon) float32 ...
    salinity           (time, depth, lat, lon) float32 ...
    salinity_bottom    (time, lat, lon) float32 ...
Attributes:
    classification_level:      UNCLASSIFIED
    distribution_statement:    Approved for public release. Distribution unli...
    downgrade_date:            not applicable
    classification_authority:  not applicable
    institution:               Fleet Numerical Meteorology and Oceanography C...
    source:                    HYCOM archive file
    history:                   archv2ncdf2d ;\nFMRC Best Dataset
    comment:                   p-grid
    field_type:                instantaneous
    Conventions:               CF-1.4, NAVO_netcdf_v1.1
    _CoordSysBuilder:          ucar.nc2.dataset.conv.CF1Convention
    cdm_data_type:             GRID
    featureType:               GRID
    location:                  Proto fmrc:GLBy0.08_930_FMRC
```

**Comment by raybellwaves** [comment]
> Why not pandas.date_range

Good point. Given the "normal" spacing of the data that makes sense.

> The problematic variable in this dataset is "tau"

Ah thanks for the digging into this for me.
