### ISSUE TITLE
bug with to_netcdf when reading dataset via THREDDS

### ISSUE THREAD

**Issue by sbiner** [pydata/xarray#5396]
I am trying to extract data for a specific station from data observations accessed via THREDDS. At first I got an error but a colleague found a way to make it work. In the code below it works if `APPLY_PATCH=True` but it crashes if `APPLY_PATCH=False`.

I do not know if this behaviour is expected and/or linked to the way the data is 'served' via THREDDS but I would never have found the way around it by myself.

```
import xarray as xr

CLEF_STATION = "MONTREAL"
NOM_VAR = 'prsn'
APPLY_PATCH = False

url_pavics = "http://pavics.ouranos.ca:8083/twitcher/ows/proxy/thredds/dodsC"
url_donnees_homo = "/".join((url_pavics, "datasets/station_obs/ECCC_AHCCD_gen2_precipitation.ncml"))

ds = xr.open_dataset(url_donnees_homo)

# data for specific station(s)
dsr = ds.sel(station=ds.station_name.str.contains(CLEF_STATION))

# apply patch
if APPLY_PATCH:
    for var in dsr.variables:
        if dsr[var].dtype == 'O':
            dsr[var].encoding = {}

# save to a netcdf file
dsr.to_netcdf("out.nc", format="NETCDF4_CLASSIC")
```

**What happened**:

When running this I get the following error

```
runfile('/Users/sbiner/cloud/OneDrive - Ouranos inc/job/stagiaires_etudiants/2021_tempete_neige/code/issue_xaray.py', wdir='/Users/sbiner/cloud/OneDrive - Ouranos inc/job/stagiaires_etudiants/2021_tempete_neige/code')
Traceback (most recent call last):

  File "src/netCDF4/_netCDF4.pyx", line 4931, in netCDF4._netCDF4.Variable.__setitem__

ValueError: cannot reshape array of size 7 into shape (1,1)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/sbiner/cloud/OneDrive - Ouranos inc/job/stagiaires_etudiants/2021_tempete_neige/code/issue_xaray.py", line 14, in <module>
    dsr.to_netcdf("out.nc", format="NETCDF4_CLASSIC")

  File "/Users/sbiner/anaconda3/envs/py38/lib/python3.8/site-packages/xarray/core/dataset.py", line 1689, in to_netcdf
    return to_netcdf(

  File "/Users/sbiner/anaconda3/envs/py38/lib/python3.8/site-packages/xarray/backends/api.py", line 1107, in to_netcdf
    dump_to_store(

  File "/Users/sbiner/anaconda3/envs/py38/lib/python3.8/site-packages/xarray/backends/api.py", line 1154, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)

  File "/Users/sbiner/anaconda3/envs/py38/lib/python3.8/site-packages/xarray/backends/common.py", line 255, in store
    self.set_variables(

  File "/Users/sbiner/anaconda3/envs/py38/lib/python3.8/site-packages/xarray/backends/common.py", line 297, in set_variables
    writer.add(source, target)

  File "/Users/sbiner/anaconda3/envs/py38/lib/python3.8/site-packages/xarray/backends/common.py", line 146, in add
    target[...] = source

  File "/Users/sbiner/anaconda3/envs/py38/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 64, in __setitem__
    data[key] = value

  File "src/netCDF4/_netCDF4.pyx", line 4933, in netCDF4._netCDF4.Variable.__setitem__

  File "<__array_function__ internals>", line 5, in broadcast_to

  File "/Users/sbiner/anaconda3/envs/py38/lib/python3.8/site-packages/numpy/lib/stride_tricks.py", line 411, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)

  File "/Users/sbiner/anaconda3/envs/py38/lib/python3.8/site-packages/numpy/lib/stride_tricks.py", line 348, in _broadcast_to
    it = np.nditer(

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (1,7)  and requested shape (1,1)
```
**What you expected to happen**:

I expect a netcdf file to be written

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.8 (default, Apr 13 2021, 12:59:45) 
[Clang 10.0.0 ]
python-bits: 64
OS: Darwin
OS-release: 19.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: fr_CA.UTF-8
LANG: fr_CA.UTF-8
LOCALE: fr_CA.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.6.1

xarray: 0.17.0
pandas: 1.2.4
numpy: 1.20.1
scipy: 1.6.2
netCDF4: 1.5.6
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.4.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2021.04.0
distributed: 2021.04.0
matplotlib: 3.3.4
cartopy: 0.18.0
seaborn: 0.11.1
numbagg: None
pint: None
setuptools: 52.0.0.post20210125
pip: 20.3.3
conda: None
pytest: None
IPython: 7.22.0
sphinx: 4.0.1

</details>

**Comment by rt17603** [comment]
I'm receiving a very similiar error when trying to work with data from the [NOAA ObsPack](https://gml.noaa.gov/ccgg/obspack/data.php) (obspack_multi-species_1_CCGGTowerInsitu_v1.0_2018-02-08). This is collated greenhouse data from global measurement stations and is in a largely standardised format.

This is an example of the code written:
```
import xarray as xr
from pathlib import Path

directory = Path("/user/work/rt17603/Input_files/obs_raw/NOAA_ObsPack_test_multi2/data/nc")
filename1 = directory / "co2_bao_tower-insitu_1_ccgg_all.nc"

home_directory = Path("/user/home/rt17603/Input_files_temp/")
out_filename1 = home_directory / str(filename1.name).replace("_all.nc", "_cut.nc")

ds1 = xr.open_dataset(filename1)
ds1.to_netcdf(out_filename1)
```

### What happened

If I just try to read this data and then immediately write this back to a netcdf file, as shown above, I receive a `ValueError: operands could not be broadcast together with remapped shapes`. I also tried this for multiple files from the ObsPack with the same result.

<details>
  <summary>Full error message</summary>

```
Traceback (most recent call last):
  File "src/netCDF4/_netCDF4.pyx", line 4916, in netCDF4._netCDF4.Variable.__setitem__
ValueError: cannot reshape array of size 612918 into shape (204306,100)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user/home/rt17603/Code_BP1/OpenGHG/Create_NOAA_nc_test_files.py", line 78, in <module>
    ds1.to_netcdf(out_filename1)
  File "/user/home/rt17603/work/environments/openghg_env/lib/python3.8/site-packages/xarray/core/dataset.py", line 1902, in to_netcdf
    return to_netcdf(
  File "/user/home/rt17603/work/environments/openghg_env/lib/python3.8/site-packages/xarray/backends/api.py", line 1072, in to_netcdf
    dump_to_store(
  File "/user/home/rt17603/work/environments/openghg_env/lib/python3.8/site-packages/xarray/backends/api.py", line 1119, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/user/home/rt17603/work/environments/openghg_env/lib/python3.8/site-packages/xarray/backends/common.py", line 265, in store
    self.set_variables(
  File "/user/home/rt17603/work/environments/openghg_env/lib/python3.8/site-packages/xarray/backends/common.py", line 307, in set_variables
    writer.add(source, target)
  File "/user/home/rt17603/work/environments/openghg_env/lib/python3.8/site-packages/xarray/backends/common.py", line 156, in add
    target[...] = source
  File "/user/home/rt17603/work/environments/openghg_env/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 69, in __setitem__
    data[key] = value
  File "src/netCDF4/_netCDF4.pyx", line 4918, in netCDF4._netCDF4.Variable.__setitem__
  File "<__array_function__ internals>", line 5, in broadcast_to
  File "/user/home/rt17603/work/environments/openghg_env/lib/python3.8/site-packages/numpy/lib/stride_tricks.py", line 411, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/user/home/rt17603/work/environments/openghg_env/lib/python3.8/site-packages/numpy/lib/stride_tricks.py", line 348, in _broadcast_to
    it = np.nditer(
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (204306,3)  and requested shape (204306,100)
```  
</details>

I can upload an example netcdf file if needed (the files are between 0.1-5MB in size). This data can also be downloaded from the [NOAA ObsPack](https://gml.noaa.gov/ccgg/obspack/data.php) pages - "obspack_multi-species_1_CCGGTowerInsitu_v1.0_2018-02-08" option. This is a printed example of the contents of one of the files:

```
Dimensions:               (obs: 204306, calendar_components: 6)
Dimensions without coordinates: obs, calendar_components
Data variables: (12/18)
    time                  (obs) datetime64[ns] ...
    time_decimal          (obs) float64 ...
    time_components       (obs, calendar_components) float64 ...
    solartime_components  (obs, calendar_components) float64 ...
    value                 (obs) float32 ...
    value_unc             (obs) float32 ...
    ...                    ...
    qcflag                (obs) object ...
    instrument            (obs) object ...
    obs_num               (obs) int32 ...
    obs_id                (obs) |S100 ...
    obspack_num           (obs) int32 ...
    obspack_id            (obs) |S200 ...
Attributes: (12/69)
    site_code:                                 BAO
    site_name:                                 Boulder Atmospheric Observator...
    site_country:                              United States
    site_country_flag:                         http://www.esrl.noaa.gov/gmd/w...
    site_latitude:                             40.05
    site_longitude:                            -105.004
    ...                                        ...
    Conventions:                               CF-1.6
    institution:                               NOAA ESRL GMD CCGG
    source:                                    tower-insitu
    references:                                see dataset_references
    title:                                     co2_bao_tower-insitu_1_ccgg_all
    history:                                   2018-02-08: File creation
```

### What was expected

Expected that the data read using xarray would be written to file. The fix suggested above would not be suitable for me as I require the data to be stored as the original dtype and not stored as object.

<details>
  <summary>Output of `xr.show_versions()`</summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1160.45.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.0
libnetcdf: 4.7.4

xarray: 0.20.1
pandas: 1.3.4
numpy: 1.21.4
scipy: 1.7.3
netCDF4: 1.5.8
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.5.1.1
nc_time_axis: 1.4.0
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: 2021.11.2
distributed: None
matplotlib: 3.5.0
cartopy: None
seaborn: None
numbagg: None
fsspec: 2021.11.1
cupy: None
pint: None
sparse: None
setuptools: 49.2.1
pip: 20.2.3
conda: None
pytest: 6.2.5
IPython: 7.30.1
sphinx: None

<\details>
