### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by zhangte113** [pydata/xarray#5488]
I am trying to deal with my meteorological data using xarray. It can work, until save dataset to netcdf file.
`dso.to_netcdf(save_file)`

`
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xarray\backends\file_manager.py", line 199, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xarray\backends\lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('D:\\longbasaba_nc\\glacier13\\meteo\\glacier132017.nc',), 'a', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\thesis_code\meteo\aws2cosipy_test.py", line 193, in <module>
    create_2D_input(csv_file, nc_file, out_nc, year)
  File "F:\thesis_code\meteo\aws2cosipy_test.py", line 157, in create_2D_input
    dso.to_netcdf(save_file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xarray\core\dataset.py", line 1809, in to_netcdf
    invalid_netcdf=invalid_netcdf,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xarray\backends\api.py", line 1059, in to_netcdf
    store = store_open(target, mode, format, group, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xarray\backends\netCDF4_.py", line 380, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xarray\backends\netCDF4_.py", line 328, in __init__
    self.format = self.ds.data_model
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xarray\backends\netCDF4_.py", line 389, in ds
    return self._acquire()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xarray\backends\netCDF4_.py", line 383, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xarray\backends\file_manager.py", line 187, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xarray\backends\file_manager.py", line 205, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src\netCDF4\_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src\netCDF4\_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'D:\\longbasaba_nc\\glacier13\\meteo\\glacier132017.nc'
[Finished in 5.2s with exit code 1]
[cmd: ['C:\\Users\\Administrator\\Documents\\Python\\Python3.7\\Scripts\\python.exe', '-u', 'F:\\thesis_code\\meteo\\aws2cosipy_test.py']]
[dir: F:\thesis_code\meteo]`

It means that xarray denied saving netcdf file.

**Comment by NiekTeeuwenVO** [comment]
Hi @zhangte113, Currently I am encountering exactly the same error, did you solve this issue?
