### ISSUE TITLE
xarray does not seem to work with timezone aware indexes

### ISSUE THREAD

**Issue by brunorigal** [pydata/xarray#5594]
Using the following code, the created index is not a time index but has object type:
```python
import numpy as np
import pandas as pd
import xarray as xr

data = xr.DataArray(np.random.random(5), dims=['time'], coords={'time': pd.date_range("2000-01-01", periods=5).tz_localize('UTC')})
print(data.time)
```
This can severely limit the practicality of time indexes. It also means that methods such as resample won't work.

**Comment by max-sixty** [comment]
I think this a problem with the repr rather than the index:

```python
  ...: print(data.time)
<xarray.DataArray 'time' (time: 5)>
array([946684800000000000, 946771200000000000, 946857600000000000,
       946944000000000000, 947030400000000000], dtype=object)
Coordinates:
  * time     (time) object 946684800000000000 ... 947030400000000000

In [2]: data.indexes['time']
Out[2]:
DatetimeIndex(['2000-01-01 00:00:00+00:00', '2000-01-02 00:00:00+00:00',
               '2000-01-03 00:00:00+00:00', '2000-01-04 00:00:00+00:00',
               '2000-01-05 00:00:00+00:00'],
              dtype='datetime64[ns, UTC]', name='time', freq='D')
```

 But I wouldn't be surprised if there were issues with this sort of index — please post issues if you find them.

**Comment by brunorigal** [comment]
For example resample yields the following error:

```python
>>> data.resample(time='1d')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bruno/miniconda3/envs/torch/lib/python3.8/site-packages/xarray/core/common.py", line 1173, in resample
    resampler = self._resample_cls(
  File "/home/bruno/miniconda3/envs/torch/lib/python3.8/site-packages/xarray/core/resample.py", line 175, in __init__
    super().__init__(*args, **kwargs)
  File "/home/bruno/miniconda3/envs/torch/lib/python3.8/site-packages/xarray/core/groupby.py", line 348, in __init__
    full_index, first_items = self._get_index_and_items(index, grouper)
  File "/home/bruno/miniconda3/envs/torch/lib/python3.8/site-packages/xarray/core/groupby.py", line 449, in _get_index_and_items
    first_items = s.groupby(grouper).first()
  File "/home/bruno/miniconda3/envs/torch/lib/python3.8/site-packages/pandas/core/series.py", line 1720, in groupby
    return SeriesGroupBy(
  File "/home/bruno/miniconda3/envs/torch/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 560, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/home/bruno/miniconda3/envs/torch/lib/python3.8/site-packages/pandas/core/groupby/grouper.py", line 719, in get_grouper
    binner, grouper, obj = key._get_grouper(obj, validate=False)
  File "/home/bruno/miniconda3/envs/torch/lib/python3.8/site-packages/pandas/core/resample.py", line 1484, in _get_grouper
    r = self._get_resampler(obj)
  File "/home/bruno/miniconda3/envs/torch/lib/python3.8/site-packages/pandas/core/resample.py", line 1476, in _get_resampler
    raise TypeError(
TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
```

**Comment by dcherian** [comment]
The resample issue is tracked in #1490. In general, (IIUC) we use numpy arrays for the data and those don't support timezones. So it's a mess (https://github.com/pydata/xarray/issues/1490#issuecomment-318183360)

**Comment by spencerkclark** [comment]
Resample happens to work now, see https://github.com/pydata/xarray/issues/1490#issuecomment-3911239706, but there are other features that still do not, e.g. the `DatetimeAccessor`:

```
>>> import pandas as pd; import xarray as xr
>>> times = pd.date_range("2000", freq="h", periods=2, tz="UTC", unit="ns")
>>> da = xr.DataArray(range(2), coords=[times], dims=["time"])
>>> da.time.dt.year
Traceback (most recent call last):
  File "<python-input-13>", line 1, in <module>
    da.time.dt.year
    ^^^^^^^^^^
  File "/Users/spencer/software/xarray/xarray/core/utils.py", line 1178, in __get__
    return self._accessor(obj)  # type: ignore[call-arg]  # assume it is a valid accessor!
           ~~~~~~~~~~~~~~^^^^^
  File "/Users/spencer/software/xarray/.pixi/envs/default/lib/python3.13/typing.py", line 1329, in __call__
    result = self.__origin__(*args, **kwargs)
  File "/Users/spencer/software/xarray/xarray/core/accessor_dt.py", line 659, in __new__
    if not _contains_datetime_like_objects(obj.variable):
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/spencer/software/xarray/xarray/core/common.py", line 2102, in _contains_datetime_like_objects
    return is_np_datetime_like(var.dtype) or contains_cftime_datetimes(var)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/spencer/software/xarray/xarray/core/common.py", line 2070, in is_np_datetime_like
    return np.issubdtype(dtype, np.datetime64) or np.issubdtype(dtype, np.timedelta64)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spencer/software/xarray/.pixi/envs/default/lib/python3.13/site-packages/numpy/_core/numerictypes.py", line 534, in issubdtype
    arg1 = dtype(arg1).type
           ~~~~~^^^^^^
TypeError: Cannot interpret 'datetime64[ns, UTC]' as a data type
```
or `interp`:
```
>>> ds.interp(time=pd.date_range("2000", freq="min", periods=2, tz="UTC", unit="ns"))
Traceback (most recent call last):
  File "<python-input-17>", line 1, in <module>
    ds.interp(time=pd.date_range("2000", freq="min", periods=2, tz="UTC", unit="ns"))
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spencer/software/xarray/xarray/core/dataset.py", line 3906, in interp
    k: _validate_interp_indexer(maybe_variable(obj, k), v)
       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spencer/software/xarray/xarray/core/dataset.py", line 3893, in _validate_interp_indexer
    if _contains_datetime_like_objects(
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        x
        ^
    ) and not _contains_datetime_like_objects(new_x):
    ^
  File "/Users/spencer/software/xarray/xarray/core/common.py", line 2102, in _contains_datetime_like_objects
    return is_np_datetime_like(var.dtype) or contains_cftime_datetimes(var)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/spencer/software/xarray/xarray/core/common.py", line 2070, in is_np_datetime_like
    return np.issubdtype(dtype, np.datetime64) or np.issubdtype(dtype, np.timedelta64)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spencer/software/xarray/.pixi/envs/default/lib/python3.13/site-packages/numpy/_core/numerictypes.py", line 534, in issubdtype
    arg1 = dtype(arg1).type
           ~~~~~^^^^^^
TypeError: Cannot interpret 'datetime64[ns, UTC]' as a data type
```
or `mean`:
```
>>> ds.time.mean()
Traceback (most recent call last):
  File "<python-input-18>", line 1, in <module>
    ds.time.mean()
    ~~~~~~~~~~~~^^
  File "/Users/spencer/software/xarray/xarray/core/_aggregations.py", line 2974, in mean
    return self.reduce(
           ~~~~~~~~~~~^
        duck_array_ops.mean,
        ^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/spencer/software/xarray/xarray/core/dataarray.py", line 3910, in reduce
    var = self.variable.reduce(func, dim, axis, keep_attrs, keepdims, **kwargs)
  File "/Users/spencer/software/xarray/xarray/core/variable.py", line 1767, in reduce
    result = super().reduce(
        func=func, dim=dim, axis=axis, keepdims=keepdims, **kwargs
    )
  File "/Users/spencer/software/xarray/xarray/namedarray/core.py", line 919, in reduce
    data = func(self.data, **kwargs)
  File "/Users/spencer/software/xarray/xarray/core/duck_array_ops.py", line 783, in mean
    return _mean(array, axis=axis, skipna=skipna, **kwargs)
  File "/Users/spencer/software/xarray/xarray/core/duck_array_ops.py", line 538, in f
    return func(values, axis=axis, **kwargs)
  File "/Users/spencer/software/xarray/xarray/computation/nanops.py", line 122, in nanmean
    return _nanmean_ddof_object(0, a, axis=axis, dtype=dtype)
  File "/Users/spencer/software/xarray/xarray/computation/nanops.py", line 115, in _nanmean_ddof_object
    data = np.sum(value, axis=axis, dtype=dtype, **kwargs)
  File "/Users/spencer/software/xarray/.pixi/envs/default/lib/python3.13/site-packages/numpy/_core/fromnumeric.py", line 2466, in sum
    return _wrapreduction(
        a, np.add, 'sum', axis, dtype, out,
        keepdims=keepdims, initial=initial, where=where
    )
  File "/Users/spencer/software/xarray/.pixi/envs/default/lib/python3.13/site-packages/numpy/_core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'Timestamp'
```
Some of these issues relate back to @dcherian's point regarding NumPy; others would likely be simpler to address. But maybe there is something more we can do with pandas extension arrays now as well.

**Comment by dcherian** [comment]
>  But maybe there is something more we can do with pandas extension arrays now as well.

I think this is the correct way to do it. Numpy datetimes are timezone-naive, so we'd need to use an ExtensionArray and make sure we propagate that. I think we are pretty well set up to do so now, thanks to @ilan-gold's efforts.

**Comment by dcherian** [comment]
This works now!

```
<xarray.DataArray 'time' (time: 5)> Size: 40B
<DatetimeArray>
['2000-01-01 00:00:00+00:00', '2000-01-02 00:00:00+00:00',
 '2000-01-03 00:00:00+00:00', '2000-01-04 00:00:00+00:00',
 '2000-01-05 00:00:00+00:00']
Length: 5, dtype: datetime64[us, UTC]
```

**Comment by amotl** [comment]
Hi. We don't know if this is related, but we are observing similar problems starting with xarray 2025.1.2. Any suggestion how to improve is much welcome.

- https://github.com/daq-tools/kotori/issues/271
