### ISSUE TITLE
NameError: name '_DType_co' is not defined

### ISSUE THREAD

**Issue by monocongo** [pydata/xarray#5631]
**What happened**: I installed a package that has xarray as a dependency. I then ran the package's console script, which resulted in the NameError shown below.

**What you expected to happen**: Successful import of the xarray package.

**Minimal Complete Verifiable Example**:
```python
$ conda create -n tstenv python=3.7
$ conda activate tstenv
(tstenv) $ pip install climate-indices
(tstenv) $ python
>>> import xarray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/james/miniconda3/envs/tstenv/lib/python3.7/site-packages/xarray/__init__.py", line 3, in <module>
    from . import testing, tutorial, ufuncs
  File "/home/james/miniconda3/envs/tstenv/lib/python3.7/site-packages/xarray/testing.py", line 8, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "/home/james/miniconda3/envs/tstenv/lib/python3.7/site-packages/xarray/core/duck_array_ops.py", line 16, in <module>
    from . import dask_array_compat, dask_array_ops, dtypes, npcompat, nputils
  File "/home/james/miniconda3/envs/tstenv/lib/python3.7/site-packages/xarray/core/npcompat.py", line 81, in <module>
    from numpy.typing import ArrayLike, DTypeLike
  File "/home/james/miniconda3/envs/tstenv/lib/python3.7/site-packages/numpy/typing/__init__.py", line 316, in <module>
    from ._dtype_like import (
  File "/home/james/miniconda3/envs/tstenv/lib/python3.7/site-packages/numpy/typing/_dtype_like.py", line 95, in <module>
    class _SupportsDType(Generic[_DType_co]):
```
 
**Anything else we need to know?**:
This does not happen if I just install xarray, so there seems to be a conflict with another dependency package at play here. Are there methods for finding namespace conflicts like this without resorting to a "manual" method of trying all the various combinations? It seems that I've included a version of another package in my requirements that has a namespace conflict with xarray -- how can I work out which this is? Or maybe a simpler solution is to not use specific versions in the `requirements.txt` of the package and instead let conda work out the correct/latest versions?

Thanks in advance for any ideas on where to look to resolve this issue (and in general for all the work that goes into xarray's care and feeding).

**Environment**:
Linux (Ubuntu 20.04)
Anaconda, Python 3.7
```
$ conda list xarray
# packages in environment at /home/james/miniconda3/envs/tstenv:
#
# Name                    Version                   Build  Channel
xarray                    0.18.2                   pypi_0    pypi
```

</details>

**Comment by max-sixty** [comment]
@monocongo does it raise an error if you try importing numpy without xarray installed?

**Comment by menzel-gfdl** [comment]
I get the same error, but can `import numpy` with/without `xarray` installed.  I'm running python 3.7.7 on RHEL 7.9 (Maipo):

```
$ pip install --upgrade pip
$ pip install xarray
$ python3
>>> import numpy
>>> import xarray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "env/lib/python3.7/site-packages/xarray/__init__.py", line 3, in <module>
    from . import testing, tutorial, ufuncs
  File "env/lib/python3.7/site-packages/xarray/testing.py", line 8, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "env/lib/python3.7/site-packages/xarray/core/duck_array_ops.py", line 16, in <module>
    from . import dask_array_compat, dask_array_ops, dtypes, npcompat, nputils
  File "env/lib/python3.7/site-packages/xarray/core/npcompat.py", line 81, in <module>
    from numpy.typing import ArrayLike, DTypeLike
  File "env/lib/python3.7/site-packages/numpy/typing/__init__.py", line 316, in <module>
    from ._dtype_like import (
  File "env/lib/python3.7/site-packages/numpy/typing/_dtype_like.py", line 95, in <module>
    class _SupportsDType(Generic[_DType_co]):
NameError: name '_DType_co' is not defined
```

**Comment by shoyer** [comment]
What happens if you just write `import numpy.typing` ?

**Comment by menzel-gfdl** [comment]
I get the same error, as expected:

```python
>>> import numpy.typing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "env/lib/python3.7/site-packages/numpy/typing/__init__.py", line 316, in <module>
    from ._dtype_like import (
  File "env/lib/python3.7/site-packages/numpy/typing/_dtype_like.py", line 95, in <module>
    class _SupportsDType(Generic[_DType_co]):
NameError: name '_DType_co' is not defined
>>> numpy.version.version
'1.21.1'
```

**Comment by shoyer** [comment]
OK, closing this over here since it seems to be a bug with numpy rather than xarray

**Comment by rhkleijn** [comment]
See https://github.com/numpy/numpy/issues/19521 
Installing typing-extensions may help when running on python 3.7.

**Comment by monocongo** [comment]
Thanks to all for your help. Installing typing-extensions did solve the problem, thanks for the heads up @rhkleijn
