### ISSUE TITLE
Parallel access to DataArray within `with` statement causes `BlockingIOError`

### ISSUE THREAD

**Issue by scottstanie** [pydata/xarray#6000]
**What happened**:

My general usage is
1. Read one DataArray from an existing dataset within a `with` statement, so the file closes at the end
2. Run it through some functions, sometimes in parallel
3. after closing the dataset, append to the dataset in a new DataArray with `.to_netcdf(existing_file, engine="h5netcdf")`.

With the setup below, I get 

`BlockingIOError: [Errno 11] Unable to create file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')`

It's entirely possible (and likely) that it's an issue with some other library that I'm using/that xarray is using... but I thought I someone might have an idea why a very similar versions of the same script succeeds, while the first one fails.

**What you expected to happen**:
No error, which happens for the 2nd version

**Minimal Complete Verifiable Example**:

For this version, I'm using [pymp](https://github.com/classner/pymp), which I'd rather not include in the MCVE, but i've had similar issues jsut using the python multiprocessing. I just wanted to post this one first.

```python
import xarray as xr
import numpy as np
import pymp


def dummy_function_parallel(stack):
    out = np.zeros(stack.shape, dtype=np.float32)
    # Also fails:
    # out = pymp.shared.array(stack.shape, dtype=np.float32)
    with pymp.Parallel(4) as p:
        for i in p.range(3):
            out[:, i] = stack[:, i] * 3
    return out

# Example of a fucntion that *doesn't* cause a failure ever
def dummy_function2(stack):
    return 2 * stack


if __name__ == "__main__":
    x, y, z = np.arange(3), np.arange(3), np.arange(3)
    data = np.random.rand(3, 3, 3)
    da = xr.DataArray(data, dims=["z", "y", "x"], coords={"x": x, "y": y, "z": z})
    da.to_dataset(name="testdata").to_netcdf("testdata.nc", engine="h5netcdf")

    with xr.open_dataset("testdata.nc") as ds:
        da = ds["testdata"]
        newstack = dummy_function_parallel(da.values)

        # This function does work without the parallel stuff
        # newstack = dummy_function2(da.values) 

        da_new = xr.DataArray(newstack, coords=da.coords, dims=da.dims)

    da_new.to_dataset(name="new_testdata").to_netcdf("testdata.nc", engine="h5netcdf")

```

Running this causes the following traceback

```python-traceback
Traceback (most recent call last):
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 199, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'h5netcdf.core.File'>, ('/data4/scott/path85/stitched/top_strip/igrams/testdata.nc',), 'a', (('decode_vlen_strings', True), ('invalid_netcdf', None))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scott/repos/insar/insar/testxr.py", line 46, in <module>
    da_new.to_dataset(name="new_testdata").to_netcdf("testdata.nc", engine="h5netcdf")
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/core/dataset.py", line 1900, in to_netcdf
    return to_netcdf(
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/api.py", line 1060, in to_netcdf
    store = store_open(target, mode, format, group, **kwargs)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 178, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 123, in __init__
    self._filename = find_root_and_group(self.ds)[0].filename
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 189, in ds
    return self._acquire()
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 181, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 187, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 205, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/h5netcdf/core.py", line 712, in __init__
    self._h5file = h5py.File(path, mode, **kwargs)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/h5py/_hl/files.py", line 442, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/h5py/_hl/files.py", line 201, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 116, in h5py.h5f.create
BlockingIOError: [Errno 11] Unable to create file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
```

**Anything else we need to know?**:

The weird part to me: If I change the end of the script so that the function runs **after** the `with` statement exits (so I'm passing the DataArray reference from a closed dataset), there's never an error. Indeed, that's how I fixed this for my real, longer script.
```python
    with xr.open_dataset("testdata.nc") as ds:
        da = ds["testdata"]
    # Now after it closed, this parallel function doesn't cause the hangup
    newstack = dummy_function_parallel(da.values)
    da_new = xr.DataArray(newstack, coords=da.coords, dims=da.dims)
    da_new.to_dataset(name="new_testdata").to_netcdf("testdata.nc", engine="h5netcdf")
```

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1062.4.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.19.0
pandas: 1.1.0
numpy: 1.19.2
scipy: 1.5.3
netCDF4: 1.5.4
pydap: None
h5netcdf: 0.11.0
h5py: 3.2.1
Nio: None
zarr: 2.8.3
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.6
cfgrib: 0.9.8.5
iris: None
bottleneck: 1.3.2
dask: 2021.01.0
distributed: 2.20.0
matplotlib: 3.3.1
cartopy: 0.19.0.post1
seaborn: None
numbagg: None
pint: 0.17
setuptools: 50.3.2
pip: 21.2.4
conda: 4.8.4
pytest: 6.2.4
IPython: 7.18.1
sphinx: 4.0.2
</details>

**Comment by kmuehlbauer** [comment]
@scottstanie That's a rough guess, but what happens if you open the file with `engine="h5netcdf"`, too? If you do not add that keyword argument it silently assumes netcdf4. That might already be the culprit because the data has to be requested via netcdf4 and written to the same file via h5netcdf.

**Comment by scottstanie** [comment]
Sorry, should have included that version of the error as well. Both give errors.

Here's when I use `engine=h5netcdf`
```
Traceback (most recent call last):
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 199, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'h5netcdf.core.File'>, ('/home/scott/testdata.nc',), 'a', (('invalid_netcdf', None),)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testxr.py", line 35, in <module>
    da_new.to_dataset(name="new_testdata").to_netcdf("testdata.nc", engine="h5netcdf")
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/core/dataset.py", line 1900, in to_netcdf
    return to_netcdf(
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/api.py", line 1060, in to_netcdf
    store = store_open(target, mode, format, group, **kwargs)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 178, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 123, in __init__
    self._filename = find_root_and_group(self.ds)[0].filename
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 189, in ds
    return self._acquire()
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 181, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 187, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 205, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/h5netcdf/core.py", line 712, in __init__
    self._h5file = h5py.File(path, mode, **kwargs)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/h5py/_hl/files.py", line 179, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
```

And here's the original
```$ python testxr.py
Traceback (most recent call last):
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 199, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'h5netcdf.core.File'>, ('/home/scott/testdata.nc',), 'a', (('invalid_netcdf', None),)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testxr.py", line 35, in <module>
    da_new.to_dataset(name="new_testdata").to_netcdf("testdata.nc", engine="h5netcdf")
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/core/dataset.py", line 1900, in to_netcdf
    return to_netcdf(
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/api.py", line 1060, in to_netcdf
    store = store_open(target, mode, format, group, **kwargs)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 178, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 123, in __init__
    self._filename = find_root_and_group(self.ds)[0].filename
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 189, in ds
    return self._acquire()
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 181, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 187, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 205, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/h5netcdf/core.py", line 712, in __init__
    self._h5file = h5py.File(path, mode, **kwargs)
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/scott/miniconda3/envs/mapping/lib/python3.8/site-packages/h5py/_hl/files.py", line 179, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
```

`xr.show_versions()`
<details>
>>> xarray.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1127.19.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.10.6
libnetcdf: 4.8.0

xarray: 0.19.0
pandas: 1.1.2
numpy: 1.21.2
scipy: 1.6.1
netCDF4: 1.5.7
pydap: None
h5netcdf: 0.11.0
h5py: 2.10.0
Nio: None
zarr: 2.8.3
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.8
cfgrib: 0.9.8.5
iris: None
bottleneck: 1.3.2
dask: 2.12.0
distributed: 2.25.0
matplotlib: 3.3.1
cartopy: 0.20.0
seaborn: None
numbagg: None
pint: 0.17
setuptools: 49.6.0.post20200814
pip: 20.0.2
conda: 4.8.4
pytest: None
IPython: 7.18.1
sphinx: 4.0.2
</details>
