### ISSUE TITLE
[Bug]: No module named 'packaging'

### ISSUE THREAD

**Issue by Peder2911** [pydata/xarray#6216]
### What happened?

I installed xarray 0.21.0 in a fresh venv and tried to import, but that raised the following exception:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python3.8/site-packages/xarray/__init__.py", line 1, in <module>
    from . import testing, tutorial, ufuncs
  File "/tmp/venv/lib/python3.8/site-packages/xarray/testing.py", line 8, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "/tmp/venv/lib/python3.8/site-packages/xarray/core/duck_array_ops.py", line 24, in <module>
    from . import dask_array_compat, dask_array_ops, dtypes, npcompat, nputils
  File "/tmp/venv/lib/python3.8/site-packages/xarray/core/dask_array_compat.py", line 4, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

### What did you expect to happen?

That the import would go fine

### Minimal Complete Verifiable Example

```python
python3.8 -m venv /tmp/venv
. /tmp/venv/bin/activate
pip install xarray==0.21.0
python -c "import xarray"
```
```


### Relevant log output

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python3.8/site-packages/xarray/__init__.py", line 1, in <module>
    from . import testing, tutorial, ufuncs
  File "/tmp/venv/lib/python3.8/site-packages/xarray/testing.py", line 8, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "/tmp/venv/lib/python3.8/site-packages/xarray/core/duck_array_ops.py", line 24, in <module>
    from . import dask_array_compat, dask_array_ops, dtypes, npcompat, nputils
  File "/tmp/venv/lib/python3.8/site-packages/xarray/core/dask_array_compat.py", line 4, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```
```


### Anything else we need to know?

_No response_

### Environment

Can't import xarray to generate this output, but relevant versions are
```
python==3.8.5
pip==20.1.1
```

**Comment by Peder2911** [comment]
I can't find the `packaging` module listed as a dependency anywhere.

**Comment by Peder2911** [comment]
I was able to reproduce the issue in the official python:3.9 docker image by running the following:
```
pip install xarray==0.21.0
python -c "import xarray"
```
Results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/xarray/__init__.py", line 1, in <module>
    from . import testing, tutorial, ufuncs
  File "/usr/local/lib/python3.9/site-packages/xarray/testing.py", line 8, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "/usr/local/lib/python3.9/site-packages/xarray/core/duck_array_ops.py", line 24, in <module>
    from . import dask_array_compat, dask_array_ops, dtypes, npcompat, nputils
  File "/usr/local/lib/python3.9/site-packages/xarray/core/dask_array_compat.py", line 4, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by Peder2911** [comment]
This all works fine with `xarray==0.20.0` so it seems that this is caused by a problem with the latest update.

**Comment by TomNicholas** [comment]
Hi @Peder2911 - thank you very much for doing this!

I think we already have a discussion going on about this problem over in #6207 though, so I think this issue is a duplicate.

**Comment by Peder2911** [comment]
Hey @TomNicholas ! Yep, that looks exactly right, this is a duplicate. Happy to see that this is already caught. Thank you for notifying me 🤜🤛

**Comment by Peder2911** [comment]
Haha, I very much doubted that I was the first to catch this, should check the issue list a little better next time.
