### ISSUE TITLE
[Bug]: define rain=((rainnc(t=17))-rainnc(t=9)))

### ISSUE THREAD

**Issue by haritha1022** [pydata/xarray#6228]
### What happened?

i just want plot particular time steps variable data
define rain=((rainnc(t=17))-rainnc(t=9)))
how can do it in python
any idea

### What did you expect to happen?

i want data only some time steps 
how can i eleminate other timesteps

### Minimal Complete Verifiable Example

```python
import xarray as xr
import cartopy.crs as ccrs
from cartopy import feature as cf
import matplotlib.pyplot as plt
import numpy as np

#Opening and reading data
data=xr.open_dataset("heavyrain3.nc")
print(data)


lon=data.lon[:]
lat=data.lat[:]


#lev_2=data.lev_2[:]

rainnc=data.rainnc[17-9]
#time=data.time[0]







ax = plt.axes(projection=ccrs.PlateCarree())

rainnc.isel(time=16, lev_2=0).plot.pcolormesh(cmap='Purples',add_colorbar=False);


#ax.set_extent([west, east, south, north])
ax.coastlines()
ax.add_feature(cf.BORDERS)

plt.savefig("rain31.jpg")
plt.show()
```

### Relevant log output

```python
raise ValueError(
ValueError: Dimensions {'time'} do not exist. Expected one or more of ('lev_2', 'lat', 'lon')
```

### Environment

Traceback (most recent call last):
  File "/home/user/Documents/IGCAR/rain/rain.py", line 39, in <module>
    rainnc.isel(time=16, lev_2=0).plot.pcolormesh(cmap='Purples',add_colorbar=False);
  File "/home/user/anaconda3/lib/python3.9/site-packages/xarray/core/dataarray.py", line 1208, in isel
    variable = self._variable.isel(indexers, missing_dims=missing_dims)
  File "/home/user/anaconda3/lib/python3.9/site-packages/xarray/core/variable.py", line 1190, in isel
    indexers = drop_dims_from_indexers(indexers, self.dims, missing_dims)
  File "/home/user/anaconda3/lib/python3.9/site-packages/xarray/core/utils.py", line 834, in drop_dims_from_indexers
    raise ValueError(
ValueError: Dimensions {'time'} do not exist. Expected one or more of ('lev_2', 'lat', 'lon')

**Comment by max-sixty** [comment]
Please review the links on producing quality examples. I'll close for now but feel free to reopen if you're up for producing one.

**Comment by haritha1022** [comment]
import xarray as xr
import cartopy.crs as ccrs
from cartopy import feature as cf
import matplotlib.pyplot as plt
import numpy as np
data=xr.open_dataset("rainncreq.nc")
print(data)
lon=data.lon[:]
lat=data.lat[:]
lev_2=data.lev_2[0]
rainnc=data.rainnc[:]
ax = plt.axes(projection=ccrs.PlateCarree())
rainnc.isel(time=0+8,lev_2=0).plot.pcolormesh(cmap='jet',vmax=100,vmin=0,add_colorbar=True);
ax.coastlines()
ax.add_feature(cf.BORDERS)
plt.savefig("rain31.jpg")
plt.show()
then it is not giving error just the data
but actually i want add the the time steps from 0 to 8
when i was 0+1+2+3....+8
then it is giving index error

File "/home/user/Documents/IGCAR/rain/rain.py", line 36, in <module>
    rainnc.isel(time=0+1+2+3+4+5+6+7+8,lev_2=0).plot.pcolormesh(cmap='jet',vmax=100,vmin=0,add_colorbar=True);
  File "/home/user/anaconda3/lib/python3.9/site-packages/xarray/core/dataarray.py", line 1208, in isel
    variable = self._variable.isel(indexers, missing_dims=missing_dims)
  File "/home/user/anaconda3/lib/python3.9/site-packages/xarray/core/variable.py", line 1193, in isel
    return self[key]
  File "/home/user/anaconda3/lib/python3.9/site-packages/xarray/core/variable.py", line 786, in __getitem__
    data = as_indexable(self._data)[indexer]
  File "/home/user/anaconda3/lib/python3.9/site-packages/xarray/core/indexing.py", line 555, in __getitem__
    return type(self)(_wrap_numpy_scalars(self.array[key]))
  File "/home/user/anaconda3/lib/python3.9/site-packages/xarray/core/indexing.py", line 524, in __getitem__
    return type(self)(_wrap_numpy_scalars(self.array[key]))
  File "/home/user/anaconda3/lib/python3.9/site-packages/xarray/core/indexing.py", line 431, in __getitem__
    return type(self)(self.array, self._updated_key(indexer))
  File "/home/user/anaconda3/lib/python3.9/site-packages/xarray/core/indexing.py", line 403, in _updated_key
    full_key.append(_index_indexer_1d(k, next(iter_new_key), size))
  File "/home/user/anaconda3/lib/python3.9/site-packages/xarray/core/indexing.py", line 176, in _index_indexer_1d
    indexer = _expand_slice(old_indexer, size)[applied_indexer]
IndexError: index 36 is out of bounds for axis 0 with size 9


hope you understand my problem
