### ISSUE TITLE
Inconsistent errors in coord construction from list of tuples vs dict

### ISSUE THREAD

**Issue by gusostow** [pydata/xarray#6362]
### What happened?

Using a `DataArray` as coordinate values for a new `DataArray` fails when the input is a list of tuples.

### What did you expect to happen?

I would expect the construction to succeed, like it does when passed a dict of coordinates.

### Minimal Complete Verifiable Example

```Python
import xarray as xr

a = xr.DataArray(range(5), coords=[("a", range(5))])

succeeds = xr.DataArray(range(5), coords=dict([("a", a.coords["a"])]))

fails = xr.DataArray(range(5), coords=[("a", a.coords["a"])])
```

### Relevant log output

```Python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "PREFIX/lib/python3.10/site-packages/xarray/core/dataarray.py", line 402, in __init__
    coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
  File "PREFIX/lib/python3.10/site-packages/xarray/core/dataarray.py", line 117, in _infer_coords_and_dims
    coord = as_variable(coord, name=dims[n]).to_index_variable()
  File "PREFIX/site-packages/xarray/core/variable.py", line 112, in as_variable
    raise TypeError(
TypeError: Using a DataArray object to construct a variable is ambiguous, please extract the data using the .data property.
```

### Environment

```

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.2 | packaged by conda-forge | (main, Mar  8 2022, 15:53:57) [GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1160.53.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: None
libnetcdf: None

xarray: 2022.3.0
pandas: 1.4.1
numpy: 1.22.3
scipy: None
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
setuptools: 60.9.3
pip: 22.0.4
conda: None
pytest: None
IPython: 8.0.1
sphinx: None
```

**Comment by keewis** [comment]
The list of tuples does not mean the same thing as the dictionary: the dictionary maps coordinate names to `DataArray` / `Variable` objects, while the list uses the names of the dimensions. In short, these are equivalent:
```python
xr.DataArray(range(5), coords=[("a", a.coords["a"])])
xr.DataArray(range(5), coords={"dim_0": ("a", a.coords["a"])})
```

Did you try doing what the error message suggests? Otherwise you might be able to just do
```python
xr.DataArray(range(5), coords=[a.coords["a"]])
```

The documentation could probably be a bit clearer about the difference, though.

**Comment by gusostow** [comment]
Ok thanks for the response, I didn't realize that the two calls weren't equivalent. Feel free to close.
