### ISSUE TITLE
trouble importing xarray, related to 'sparse' module?

### ISSUE THREAD

**Issue by egdeist** [pydata/xarray#6756]
### What is your issue?

Hello,
I am having some kind of versioning or compatibility problem I think... 
I have used xarray in the past successfully! But I went back to run some old code and as soon as I run 'import xarray' I get an error: 
>>> import xarray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Emma\anaconda3\lib\site-packages\xarray\__init__.py", line 1, in <module>
    from . import testing, tutorial, ufuncs
  File "C:\Users\Emma\anaconda3\lib\site-packages\xarray\testing.py", line 8, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "C:\Users\Emma\anaconda3\lib\site-packages\xarray\core\duck_array_ops.py", line 24, in <module>
    from . import dask_array_compat, dask_array_ops, dtypes, npcompat, nputils
  File "C:\Users\Emma\anaconda3\lib\site-packages\xarray\core\dask_array_compat.py", line 5, in <module>
    from .pycompat import dask_version
  File "C:\Users\Emma\anaconda3\lib\site-packages\xarray\core\pycompat.py", line 63, in <module>
    sp = DuckArrayModule("sparse")
  File "C:\Users\Emma\anaconda3\lib\site-packages\xarray\core\pycompat.py", line 22, in __init__
    duck_array_version = LooseVersion(duck_array_module.__version__)
AttributeError: module 'sparse' has no attribute '__version__'

I think this must be related to some python package updates? Not totally sure... 
Any help would be much appreciated!

**Comment by egdeist** [comment]
Sorry! Figured this out... was related to another Python package I use: [QuTiP](https://github.com/qutip), which must have some other "sparse" that got mixed up in the importing. I just uninstalled Qutip so I could use xarray. I guess they are not compatible, for now.
