### ISSUE TITLE
Cannot re-index or align objects with conflicting indexes

### ISSUE THREAD

**Issue by jamesstidard** [pydata/xarray#7005]
### What happened?

I'm looking to rename the values of indices of an existing dataset, for both regular and multi-index. i.e. you might start with a dataset with and index `[1,2,3]` and you want to rename those to `["foo", "bar", "bar"]`.

I appear to be able to rename a couple using the method I've written, though renaming a second multi-index in the same `xr.Dataset` causes a `ValueError` I am struggling to interpret.

> cannot re-index or align objects with conflicting indexes found for the following dimensions: 'x' (2 conflicting indexes)
Conflicting indexes may occur when
> - they relate to different sets of coordinate and/or dimension names
> - they don't have the same type
> - they may be used to reindex data along common dimensions

### What did you expect to happen?

I start with the `xr.Datset`:

```
xarray.DataArray (x: 6, y: 6, z: 3)>
array(...)
Coordinates:
  * x            (x) object MultiIndex
  * x_one    (x) object 'a' 'a' 'b' 'b' 'c' 'c'
  * x_two    (x) int64 0 1 0 1 0 1
  * y            (y) object MultiIndex
  * y_one    (y) object 'a' 'a' 'b' 'b' 'c' 'c'
  * y_two    (y) int64 0 1 0 1 0 1
  * z            (z) int64 0 1 2
 ```

And remap the `z`, `x_one`, and `y_one` values to:

```
xarray.DataArray (x: 6, y: 6, z: 3)>
array(...)
Coordinates:
  * x            (x) object MultiIndex
  * x_one    (x) object 'aa' 'aa' 'bb' 'bb' 'cc' 'cc'
  * x_two    (x) int64 0 1 0 1 0 1
  * y            (y) object MultiIndex
  * y_one    (y) object 'aa' 'aa' 'bb' 'bb' 'cc' 'cc'
  * y_two    (y) int64 0 1 0 1 0 1
  * z            (z) <U4 'zero' 'one' 'two'
```

### Minimal Complete Verifiable Example

```Python
import numpy as np
import pandas as pd
import xarray as xr


def map_coords(ds, *, name, mapping):
    """
    Takes a xarray dataset's coordinate values and updates
    them with the given the provided mapping.

    Can handle both regular indices and multi-level indices.

    ds: the datasets
    name: name of the coordinate to update
    mapping: dictionary, key of old value, value of new value.
    """
    coord = ds.coords[name]
    old_values = coord.values.tolist()
    new_values = [mapping[v] for v in old_values]
    ds.coords[name] = xr.DataArray(new_values, coords=coord.coords)
    ds.coords[name].attrs = dict(coord.attrs)

midx = pd.MultiIndex.from_product([list("abc"), [0, 1]], names=("x_one", "x_two"))
midy = pd.MultiIndex.from_product([list("abc"), [0, 1]], names=("y_one", "y_two"))

mda = xr.DataArray(np.random.rand(6, 6, 3), [("x", midx), ("y", midy), ("z", range(3))])

map_coords(mda, name="z", mapping={0: "zero", 1: "one", 2: "two"}). # success
map_coords(mda, name="x_one", mapping={"a": "aa", "b": "bb", "c": "cc"})  # success
map_coords(mda, name="y_one", mapping={"a": "aa", "b": "bb", "c": "cc"})  # ValueError
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
Traceback (most recent call last):
  File "./main.py", line 30, in <module>
    map_coords(mda, name="y_one", mapping={"a": "aa", "b": "bb", "c": "cc"})
  File "./main.py", line 20, in map_coords
    ds.coords[name] = xr.DataArray(new_values, coords=coord.coords)
  File "./.venv/lib/python3.10/site-packages/xarray/core/coordinates.py", line 32, in __setitem__
    self.update({key: value})
  File "./.venv/lib/python3.10/site-packages/xarray/core/coordinates.py", line 162, in update
    coords, indexes = merge_coords(
  File "./.venv/lib/python3.10/site-packages/xarray/core/merge.py", line 561, in merge_coords
    aligned = deep_align(
  File "./.venv/lib/python3.10/site-packages/xarray/core/alignment.py", line 827, in deep_align
    aligned = align(
  File "./.venv/lib/python3.10/site-packages/xarray/core/alignment.py", line 764, in align
    aligner.align()
  File "./.venv/lib/python3.10/site-packages/xarray/core/alignment.py", line 550, in align
    self.assert_no_index_conflict()
  File "./.venv/lib/python3.10/site-packages/xarray/core/alignment.py", line 319, in assert_no_index_conflict
    raise ValueError(
ValueError: cannot re-index or align objects with conflicting indexes found for the following dimensions: 'x' (2 conflicting indexes)
Conflicting indexes may occur when
- they relate to different sets of coordinate and/or dimension names
- they don't have the same type
- they may be used to reindex data along common dimensions
```

### Anything else we need to know?

I may also not be doing this remapping in the best way, this has been the easiest way I've found to do it. So maybe part of the problem is that, so open to alternative methods as well.

Thanks.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.4 (main, Mar 28 2022, 15:33:01) [Clang 13.1.6 (clang-1316.0.21.2)]
python-bits: 64
OS: Darwin
OS-release: 21.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: None

xarray: 2022.6.0
pandas: 1.4.4
numpy: 1.23.2
scipy: 1.9.1
netCDF4: None
pydap: None
h5netcdf: 1.0.2
h5py: 3.7.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 63.4.3
pip: 22.2.2
conda: None
pytest: None
IPython: None
sphinx: None
</details>

**Comment by benbovy** [comment]
Hi @jamesstidard,

> causes a ValueError I am struggling to interpret.

I agree that the error message is not very informative. This could be improved.

The problem in your example is located here:

```python
def map_coords(ds, *, name, mapping):
    ...
    ds.coords[name] = xr.DataArray(new_values, coords=coord.coords)
    ...
```

Since v2022.6.0, multi-index level coordinates are real coordinates. What happens is that when you update "x_one" it invalidates the multi-index "x" - "x_one" - "x_two" in the DataArray:

```python
...
map_coords(mda, name="z", mapping={0: "zero", 1: "one", 2: "two"}). # success
map_coords(mda, name="x_one", mapping={"a": "aa", "b": "bb", "c": "cc"})  # success

# the 'x', 'x_one' and 'x_two' indexes are all equal
mda.xindexes["x_one"].equals(mda.xindexes["x"]) and mda.xindexes["x_one"].equals(mda.xindexes["x_two"])
# True

# the 'x' and 'x_two' indexes are identical, but not the 'x_one' index!
mda.xindexes["x"] is mda.xindexes["x_two"]
# True
mda.xindexes["x"] is mda.xindexes["x_one"]
# False
```

Which explains the alignment error when you further try to update the DataArray.

I'm actually surprised that it doesn't raise any error at that point, like this:

```python
mda = xr.DataArray(np.random.rand(6, 6, 3), [("x", midx), ("y", midy), ("z", range(3))])
mda.coords["x_two"] = ("x", range(6))
# ValueError: cannot set or update variable(s) 'x_two', which would corrupt the following
# index built from coordinates 'x', 'x_one', 'x_two':
# <xarray.core.indexes.PandasMultiIndex object at 0x1689cc190>
```

It seems like a bug.

Either way, you shouldn't try updating a single coordinate that is part of a multi-coordinate index, which is assumed immutable. Instead, you could use `reset_index`/`set_index` before/after updating the labels of one level coordinate. You could also replace the whole index and its coordinates at once (example below). I wouldn't rely too much on the latter option, though, as such special case for `pd.MultiIndex` might eventually be deprecated in Xarray.

```python
new_midx = midx.set_levels(["aa", "bb", "cc"], level="x_one")
mda.coords["x"] = new_midx
```

**Comment by jamesstidard** [comment]
Hi @benbovy,

Thanks for the detailed response.

Yeah, that it was only raising for the second multi indexing map, does seem like a bug in that case, I'll leave the ticket open to track that.

I didn't stumble on the `set_levels` function while skimming though the docs, thanks. I've updated my function to make use of that. I'm hoping things should be safe with this, and I'm correctly replacing things in the correct order.

For anyone else who's looking to do the same, or for anyone to tell me what I'm doing is not safe, or there's a simpler way, here's the updated function:

```python
import numpy as np
import pandas as pd
import xarray as xr


def map_coords(ds, *, name, mapping):
    """
    Takes a xarray dataset's coordinate values and updates
    them with the given the provided mapping. In-place.

    Can handle both regular indices and multi-level indices.

    ds: An xr.Datset
    name: name of the coordinate to update
    mapping: dictionary, key of old value, value of new value.
    """
    # all attrs seem to get dropped on coords even if only
    # one is altered. Hold on to them and reapply after
    coord_attrs = {c: ds[c].attrs for c in ds.coords}

    if ds.indexes.is_multi(name):
        target = name
        parent = ds.indexes[target].name

        if target == parent:
            valid_targets = ds.indexes[parent].names
            raise ValueError(
                f"Can only map levels of a MultiIndex, not the MultiIndex "
                f"itself. Target one of {valid_targets}",
            )

        multi_index = ds.indexes[parent]
        level_values = dict(zip(multi_index.names, multi_index.levels))
        new_values = [mapping[v] for v in level_values[name]]
        ds.coords[parent] = multi_index.set_levels(new_values, level=target)
    else:
        old_values = ds.coords[name].values
        new_values = [mapping[v] for v in old_values]
        ds[name] = new_values

    # reapply attrs
    for coord, attrs in coord_attrs.items():
        ds[coord].attrs = attrs


midx = pd.MultiIndex.from_product([list("abc"), [0, 1]], names=("x_one", "x_two"))
midy = pd.MultiIndex.from_product([list("abc"), [0, 1]], names=("y_one", "y_two"))
mda = xr.DataArray(np.random.rand(6, 6, 3), [("x", midx), ("y", midy), ("z", range(3))])

map_coords(mda, name="z", mapping={0: "zero", 1: "one", 2: "two"})
map_coords(mda, name="x_one", mapping={"a": "aa", "b": "bb", "c": "cc"})
map_coords(mda, name="y_one", mapping={"a": "aa", "b": "bb", "c": "cc"})

print(mda)
```

**Comment by benbovy** [comment]
I'm closing this issue as the example in the top-comment now raises more meaningful errors (trying to update the variable would corrupt the multi-index).

Also the updated function above outputs a warning here:

```python
        ds.coords[parent] = multi_index.set_levels(new_values, level=target)
```

There preferred way to re-assign the new multi-index to the dataset is now:

```python
        new_multi_index = multi_index.set_levels(new_values, level=target)
        new_coords = xr.Coordinates.from_pandas_multiindex(new_multi_index, dim=parent)
        ds.assign_coords(new_coords)
```
