### ISSUE TITLE
"OSError: [Errno 22] Invalid argument" when loading and processing .grib file

### ISSUE THREAD

**Issue by layadas** [pydata/xarray#7007]
### What is your issue?

I am trying to load and extract data from a `.grib` file on Windows 10. I get the same error `OSError: [Errno 22] Invalid argument` for a number of functions.
First,
```
ds = xr.load_dataset(os.path.join(data_folder, file_name), engine="cfgrib")
```
raises the error, so I use
```
ds = xr.open_dataset(os.path.join(data_folder, file_name), engine="cfgrib")
```
This works fine. Next, when I try to convert the `Dataset` or `DataArray` to `DataFrame` or `NDArray` with any of the following commands, then I get the error:
```
ds.to_dataframe()  # raises error
da = ds.var1
da.to_numpy  # raises error
```
Then I tried to access the variable manually, and I still get the same error:
```
v = da.variable.item()
v1 = v.data  # raises error
```
Every time the error ends with: `OSError: [Errno 22] Invalid argument`. A sample error when I use `load_dataset` is:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 3, in <module>
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\backends\api.py", line 271, in load_dataset
    return ds.load()
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\dataset.py", line 741, in load
    v.load()
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\variable.py", line 461, in load
    self._data = np.asarray(self._data)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\indexing.py", line 653, in __array__
    self._ensure_cached()
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\indexing.py", line 650, in _ensure_cached
    self.array = NumpyIndexingAdapter(np.asarray(self.array))
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\indexing.py", line 623, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\indexing.py", line 524, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\xarray_plugin.py", line 144, in __getitem__
    return xr.core.indexing.explicit_indexing_adapter(
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\indexing.py", line 815, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\xarray_plugin.py", line 150, in _getitem
    return self.array[key]
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\dataset.py", line 342, in __getitem__
    message = self.index.get_field(message_ids[0])  # type: ignore
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\messages.py", line 472, in get_field
    return ComputedKeysAdapter(self.fieldset[message_id], self.computed_keys)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\messages.py", line 332, in __getitem__
    return self.message_from_file(file, offset=item)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\messages.py", line 328, in message_from_file
    return Message.from_file(file, offset, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\messages.py", line 91, in from_file
    file.seek(offset)
OSError: [Errno 22] Invalid argument
```
When I use `ds.to_dataframe()`, the error is:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\dataset.py", line 5898, in to_dataframe
    return self._to_dataframe(ordered_dims=ordered_dims)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\dataset.py", line 5862, in _to_dataframe
    data = [
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\dataset.py", line 5863, in <listcomp>
    self._variables[k].set_dims(ordered_dims).values.reshape(-1)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\variable.py", line 1560, in set_dims
    expanded_data = self.data
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\variable.py", line 354, in data
    return self.values
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\variable.py", line 527, in values
    return _as_array_or_item(self._data)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\variable.py", line 267, in _as_array_or_item
    data = np.asarray(data)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\indexing.py", line 653, in __array__
    self._ensure_cached()
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\indexing.py", line 650, in _ensure_cached
    self.array = NumpyIndexingAdapter(np.asarray(self.array))
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\indexing.py", line 623, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\indexing.py", line 524, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\xarray_plugin.py", line 144, in __getitem__
    return xr.core.indexing.explicit_indexing_adapter(
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\xarray\core\indexing.py", line 815, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\xarray_plugin.py", line 150, in _getitem
    return self.array[key]
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\dataset.py", line 342, in __getitem__
    message = self.index.get_field(message_ids[0])  # type: ignore
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\messages.py", line 472, in get_field
    return ComputedKeysAdapter(self.fieldset[message_id], self.computed_keys)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\messages.py", line 332, in __getitem__
    return self.message_from_file(file, offset=item)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\messages.py", line 328, in message_from_file
    return Message.from_file(file, offset, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\WeatherProject\lib\site-packages\cfgrib\messages.py", line 91, in from_file
    file.seek(offset)
OSError: [Errno 22] Invalid argument
```

**Comment by dcherian** [comment]
Hi @layadas : Perhaps this [answer](https://stackoverflow.com/questions/63194917/python-how-to-solve-oserror-errno-22-invalid-argument) helps?

Closing since this does not seem to be an xarray issue.
