### ISSUE TITLE
Zarr error when trying to overwrite part of existing store

### ISSUE THREAD

**Issue by TomNicholas** [pydata/xarray#7403]
### What happened?

`to_zarr` threw an error when I tried to overwrite part of an existing zarr store.

### What did you expect to happen?

With mode `w` I was expecting it to overwrite part of the store with no complaints. 

I expected that because that's what the docstring of `to_zarr` says:

> `mode ({"w", "w-", "a", "r+", None}, optional)` – Persistence mode: “w” means create (overwrite if exists); “w-” means create (fail if exists); “a” means override existing variables (create if does not exist);

The default mode is "w", so I was expecting it to overwrite.

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import numpy as np
np.random.seed(0)

ds = xr.Dataset()
ds["data"] = (['x', 'y'], np.random.random((100,100)))
ds.to_zarr("test.zarr")
print(ds["data"].mean().compute())
# returns array(0.49645889) as expected

ds = xr.open_dataset("test.zarr", engine='zarr', chunks={})
ds["data"].mean().compute()
print(ds["data"].mean().compute())
# still returns array(0.49645889) as expected

ds.to_zarr("test.zarr", mode="a")


```python
<xarray.DataArray 'data' ()>
array(0.49645889)
<xarray.DataArray 'data' ()>
array(0.49645889)
Traceback (most recent call last):
  File "/home/tom/Documents/Work/Code/experimentation/bugs/datatree_nans/mwe_xarray.py", line 16, in <module>
    ds.to_zarr("test.zarr")
  File "/home/tom/miniconda3/envs/xrdev3.9/lib/python3.9/site-packages/xarray/core/dataset.py", line 2091, in to_zarr
    return to_zarr(  # type: ignore
  File "/home/tom/miniconda3/envs/xrdev3.9/lib/python3.9/site-packages/xarray/backends/api.py", line 1628, in to_zarr
    zstore = backends.ZarrStore.open_group(
  File "/home/tom/miniconda3/envs/xrdev3.9/lib/python3.9/site-packages/xarray/backends/zarr.py", line 420, in open_group
    zarr_group = zarr.open_group(store, **open_kwargs)
  File "/home/tom/miniconda3/envs/xrdev3.9/lib/python3.9/site-packages/zarr/hierarchy.py", line 1389, in open_group
    raise ContainsGroupError(path)
zarr.errors.ContainsGroupError: path '' contains a group
```
```


### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

_No response_

### Anything else we need to know?

I would like to know what the intended result is supposed to be here, so that I can make sure datatree behaves the same way.

### Environment

Main branch of xarray, zarr v2.13.3

**Comment by slevang** [comment]
Your MCVE has `mode="a"`, is that intentional? As far as defaults, what the docstring says is:

> The default mode is “a” if append_dim is set. Otherwise, it is “r+” if region is set and w- otherwise.

So without specifying mode, you get `mode="w-"` which will not overwrite anything. With `mode="a"`, your MCVE runs fine for me.

From using these a bit, my understanding is:

- `mode="w-"` is the safe default that won't overwrite anything
- `mode="w"` is only if you want to rewrite the **entire** zarr store, not for rewriting a subset of existing data
- `mode="r+"` is for modifying values on some subset of the existing store specified by the index with `region`, but doesn't allow changing any dimension sizes
- `mode="a"` is for completely overwriting existing variables*, appending new variables, or appending data along an existing dimension, paired with `append_dim`

\* I actually didn't realize this behavior until testing it out just now, but it is described in the docstring

**Comment by jhamman** [comment]
I think the above example can be reduced to just: 

```python
ds = xr.Dataset()
ds.to_zarr('test.zarr')
ds.to_zarr('test.zarr')
```

An interesting data point here is that `to_netcdf` defaults to `w` mode. And this works fine:

```python
ds = xr.Dataset()
ds.to_netcdf('test.nc')
ds.to_netcdf('test.nc')
```

Personally, I'll make the argument that we should switch (carefully) from `-w` to `w` for the default case.

**Comment by slevang** [comment]
> Personally, I'll make the argument that we should switch (carefully) from `-w` to `w` for the default case.

This makes sense in principal for consistency with other i/o methods, but I think could go very wrong in practice, especially for inexperienced users. 

For example, a misplaced command of `ds.to_zarr("gs://bucket_name")` with default `mode="w"` overwrites a user's entire bucket, and same thing for local storage. `to_netcdf` doesn't have the capability to `rm -r` a directory, so I would argue `to_zarr(mode="w")` is **much** more dangerous.
