### ISSUE TITLE
ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf', 'scipy']. 

### ISSUE THREAD

**Issue by xeimyname1** [pydata/xarray#7754]
### What is your issue?

Hi,

 I am using python 3.1 1.3, I am encountering this error when running a package

```
Traceback (most recent call last):
File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/climate_indices/main.py", line 1671, in main
input_type = _validate_args(arguments)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/climate_indices/main.py", line 108, in _validate_args
with xr.open_dataset(args.netcdf_precip) as dataset_precip:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/xarray/backends/api.py", line 510, in open_dataset
engine = plugins.guess_engine(filename_or_obj)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/xarray/backends/plugins.py", line 177, in guess_engine
raise ValueError(error_msg)
ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf', 'scipy']. Consider explicitly selecting one of the installed engines via the engine parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html
Traceback (most recent call last):
File "/Users/24715447/anaconda3/envs/climate/bin/process_climate_indices", line 8, in
sys.exit(main())
^^^^^^
File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/climate_indices/main.py", line 1671, in main
input_type = _validate_args(arguments)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/climate_indices/main.py", line 108, in _validate_args
with xr.open_dataset(args.netcdf_precip) as dataset_precip:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/xarray/backends/api.py", line 510, in open_dataset
engine = plugins.guess_engine(filename_or_obj)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/24715447/anaconda3/envs/climate/lib/python3.11/site-packages/xarray/backends/plugins.py", line 177, in guess_engine
raise ValueError(error_msg)
ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf', 'scipy']. Consider explicitly selecting one of the installed engines via the engine parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html
```

I have tried installing xarray dependencies as given in the links. 
```
pip install xarray[io]
conda install conda-forge netcdf4 h5netcdf scipy
```
I can confirm that all dependencies were installed but the same error pops out after trying again.  
 Any advice on how to solve the issue?

**Comment by headtr1ck** [comment]
The error message tells that the backends are installed and can be found by xarray.

What exactly did you try to open? A local file? If yes, can you provide the name of this file?

**Comment by xeimyname1** [comment]
Yes. I am trying to open a local file. 
Filename is auchirps_monthly_bydekad_e11.nc

**Comment by headtr1ck** [comment]
What happens when you specify the netcdf4 engine directly? (Assuming it is a nc4 and not nc3 file).

**Comment by xeimyname1** [comment]
Hi, thanks for the response. I have solved it already. 

1. I downgraded my python version to 3.9 from 3.11
2. Conda install for xarray dependencies worked at this version 
3. The ValueError is a file problem. Tried using it on a different file and its works perfectly.
