### ISSUE TITLE
 TypeError: 'NoneType' object is not callable when joining netCDF files. Works when ran interactively.

### ISSUE THREAD

**Issue by paul0207** [pydata/xarray#7814]
### What is your issue?

I'm trying to join multiple netCDF files with the following:

import xarray as xr
combined = xr.open_mfdataset('Burst*.nc',combine="nested", concat_dim="time", group="Data/Burst")
combined.to_netcdf('nc_combined.nc')

When running the lines interactively, everything works, but when running it as a script I get the following error multiple times:
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 246, in del
TypeError: 'NoneType' object is not callable

Thanks,
Paul

**Comment by dcherian** [comment]
We;ll need a reproducible example

**Comment by paul0207** [comment]
> We;ll need a reproducible example
Deepak, thanks for replying, I have attached a couple of my netCDF files. Hopefully these will help for reproducing the issue.

[Archive.zip](https://github.com/pydata/xarray/files/11400070/Archive.zip)

**Comment by kmuehlbauer** [comment]
@paul0207 Thanks for providing the datafiles. I can't reproduce on my machine. Please provide more information, the output of `xr.show_versions()` would help and a complete traceback of the error you are experiencing. 

A complete list of installed Python Packages would be nice (eg. by `pip list`), too.

Another couple of questions to get some more insight:

- Does this happen only with these special files, or do you experience this every time?
- Does the problem persists when specifying `engine="netcdf4"` or `engine="h5netcdf"` in the call to `open_mfdataset`?
- Does this also happen, if you open the files one-by-one (with `xr.open_dataset`) and combine the Datasets with `xr.concat`?

**Comment by paul0207** [comment]
Thanks Kai,
I have attached the output of `xr.show_versions()` and of `pip list`.

> Does this happen only with these special files, or do you experience this every time?
I tried with two netcdf files from https://www.northwestknowledge.net/metdata/data/ and got the same _TypeError: 'NoneType' object is not callable_

> Does the problem persists when specifying engine="netcdf4" or engine="h5netcdf" in the call to open_mfdataset?
Only engine="netcdf4" works as a parameter but I get the same error, h5netcdf is not recognized as an engine.

> Does this also happen, if you open the files one-by-one (with xr.open_dataset) and combine the Datasets with xr.concat?
Yes, opening files with xr.open_dataset and combining them with xr.concat gives the same error.

Please note the following that I just realized, the resulting combined netCDF file is actually created even though the errors are displayed.
Also, like I mention in my first message, if I run the commands line by line in the python console no error message is displayed, this happens only when the code is ran as a script.

Paul

[pip_list.txt](https://github.com/pydata/xarray/files/11410616/pip_list.txt)
[xr.show_versions.txt](https://github.com/pydata/xarray/files/11410617/xr.show_versions.txt)

**Comment by keewis** [comment]
I *can* reproduce this locally:
- download the files
- use `mamba create -n test python=3.9 xarray=2023.04.2 netcdf4=1.6.3` to create the environment (note: no `dask`)
- use `pip install "dask[array]"` to install `dask` (does not pull `distributed` like the package from `conda-forge`)
- put the code into a script and execute it

For reference, the full traceback is:
```pytb
Exception ignored in: <function CachingFileManager.__del__ at 0x7fbdb237b430>
Traceback (most recent call last):
  File "/home/jmagin/.local/opt/mambaforge/envs/test/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 246, in __del__
TypeError: 'NoneType' object is not callable
```

As far as I can tell, this means we're using something from `distributed` with a broken fallback, since the error goes away as soon as I *install* `distributed`.

**Comment by keewis** [comment]
Actually, it goes away with `pip install jinja2`. We don't use `jinja2` at all, so either this is some kind of weird effect on garbage collection (a timing issue?), or `dask` is doing something differently as soon as `jinja2` is available.

cc @jrbourbeau
