### ISSUE TITLE
decide on how to handle `empty_like`

### ISSUE THREAD

**Issue by hmaarrfk** [pydata/xarray#7940]
### Is your feature request related to a problem?

calling `np.empty_like` seems to be instantiating the whole array.

```python
from xarray.tests import InaccessibleArray
import xarray as xr
import numpy as np

array = InaccessibleArray(np.zeros((3, 3), dtype="uint8"))
da = xr.DataArray(array, dims=["x", "y"])

np.empty_like(da)
```

```python
Traceback (most recent call last):
  File "/home/mark/t.py", line 8, in <module>
    np.empty_like(da)
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/xarray/core/common.py", line 165, in __array__
    return np.asarray(self.values, dtype=dtype)
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/xarray/core/dataarray.py", line 732, in values
    return self.variable.values
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/xarray/core/variable.py", line 614, in values
    return _as_array_or_item(self._data)
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/xarray/core/variable.py", line 314, in _as_array_or_item
    data = np.asarray(data)
  File "/home/mark/mambaforge/envs/dev/lib/python3.9/site-packages/xarray/tests/__init__.py", line 151, in __array__
    raise UnexpectedDataAccess("Tried accessing data")
xarray.tests.UnexpectedDataAccess: Tried accessing data
```

### Describe the solution you'd like

I'm not too sure. This is why I raised this as a "feature" and not a bug. 

On one hand, it is pretty hard to "get" the underlying class.

Is it a:

* numpy array
* a lazy thing that looks like a numpy array?
* a dask array when it is dask?

I think that there are also some nuances between:

1. Loading an nc file from a file (where things might be handled by dask even though you don't want them to be)
2. Creating your xarray from in memory.

### Describe alternatives you've considered

for now, i'm trying to avoid `empty_like` or `zeros_like`.

In general, we haven't seen much benefit from dask and cuda still needs careful memory management.

**Comment by headtr1ck** [comment]
Maybe you could use a shallow copy instead?

**Comment by hmaarrfk** [comment]
a little more context.

For some "slow to load" datasets, this can accidentally load the whole thing when one isn't ready for it.

**Comment by keewis** [comment]
I might be wrong, but I *think* those are not ufuncs, and since `xarray` [doesn't implement `__array_function__`](https://github.com/pydata/xarray/issues/3917) `np.empty_like(da)` results in something like `np.empty_like(np.asarray(da))`.

However, `xr.zeros_like` shows the same behavior, so there might be something else going on.

**Comment by hmaarrfk** [comment]
zeros_like is essentially `empty_like`
https://github.com/numpy/numpy/blob/0e2af8463c2f005ba46341bcf675f12e0f705fee/numpy/core/numeric.py#L127

**Comment by keewis** [comment]
there might be something wrong with the way `InaccessibleArray` is implemented, at least for this use case: `np.zeros_like(array)` doesn't work, so `np.zeros_like(da)` has no chance of working.

**Comment by hmaarrfk** [comment]
> Note that there's a difference between xr.zeros_like and np.zeros_like.

Ahhhh! thanks

**Comment by keewis** [comment]
I didn't check if modifying `_full_like_variable` as proposed doesn't break anything else, though
