### ISSUE TITLE
Maximum recursion calling `np.divide` with `DataArray` as `where` argument

### ISSUE THREAD

**Issue by ZedThree** [pydata/xarray#7965]
### What happened?

Calling `np.divide()` passing a bool expression involving a `DataArray` results in a `RecursionError` starting at `apply_ufunc`. Passing `DataArray.data` works fine.

### Minimal Complete Verifiable Example

```Python
import numpy as np
import xarray as xr

N = 10
array = np.random.random((N,))
da = xr.DataArray(np.random.random((N,)), dims=("x",), coords={"x": np.arange(N)})

# This works
print(np.divide(array, da, where=(da > 0.2).data))

# This gives recursion error
print(np.divide(array, da, where=da > 0.2))
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
Traceback (most recent call last):
  File "divide_recursion_mvce.py", line 7, in <module>
    print(np.divide(array, da, where=da > 0.2))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/xarray/core/arithmetic.py", line 86, in __array_ufunc__
    return apply_ufunc(
           ^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/xarray/core/computation.py", line 1197, in apply_ufunc
    return apply_dataarray_vfunc(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/xarray/core/computation.py", line 304, in apply_dataarray_vfunc
    result_var = func(*data_vars)
                 ^^^^^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/xarray/core/computation.py", line 761, in apply_variable_ufunc
    result_data = func(*input_data)
                  ^^^^^^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/xarray/core/arithmetic.py", line 86, in __array_ufunc__
    return apply_ufunc(
           ^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/xarray/core/computation.py", line 1210, in apply_ufunc
    return apply_array_ufunc(func, *args, dask=dask)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

...

  File "venv/lib64/python3.11/site-packages/xarray/core/computation.py", line 1210, in apply_ufunc
    return apply_array_ufunc(func, *args, dask=dask)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/xarray/core/computation.py", line 815, in apply_array_ufunc
    if any(is_chunked_array(arg) for arg in args):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/xarray/core/computation.py", line 815, in <genexpr>
    if any(is_chunked_array(arg) for arg in args):
           ^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/xarray/core/pycompat.py", line 99, in is_chunked_array
    return is_duck_dask_array(x) or (is_duck_array(x) and hasattr(x, "chunks"))
           ^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/xarray/core/pycompat.py", line 95, in is_duck_dask_array
    return is_duck_array(x) and is_dask_collection(x)
                                ^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/xarray/core/pycompat.py", line 87, in is_dask_collection
    if module_available("dask"):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/xarray/core/utils.py", line 1160, in module_available
    return importlib.util.find_spec(module) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 103, in find_spec
  File "<frozen importlib._bootstrap>", line 1080, in _find_spec
  File "<frozen importlib._bootstrap>", line 924, in find_spec
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Environment

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.11.3 (main, Apr 27 2023, 22:08:21) [GCC]
python-bits: 64
OS: Linux
OS-release: 6.3.9-1-default
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: ('en_GB', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.9.3-development

xarray: 2023.6.0
pandas: 1.5.3
numpy: 1.25.0
scipy: 1.11.1
netCDF4: 1.6.4
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: 3.7.2
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.5.0
pip: 23.1.2
conda: None
pytest: 7.4.0
mypy: None
IPython: 8.14.0
sphinx: None
</details>

**Comment by dcherian** [comment]
Well I was going to say that
>  I don't think this can work. `apply_ufunc` does not unwrap Xarray objects in `kwargs` like `where` here. Using `.data` is your best approach I think

Turns out it does work on numpy 1.24.0 and xarray 2023.06.0. You have numpy 1.25.0 and xarray 2023.06.0.

This [release note](https://numpy.org/doc/stable/release/1.25.0-notes.html#array-likes-that-define-array-ufunc-can-now-override-ufuncs-if-used-as-where) and [PR](https://github.com/numpy/numpy/pull/23240) seems like the relevant changes. And it seems like we need to do something with our `where` implementation.

cc @keewis @shoyer
