### ISSUE TITLE
In `Dataset.to_zarr` cannot specify to not write empty chunks when appending to existing store

### ISSUE THREAD

**Issue by RKuttruff** [pydata/xarray#8009]
### What happened?

I'm trying to append to a very sparse zarr store. When initially creating (or overwriting) the store, I can specify `{'write_empty_chunks': False}` for the data variables in the dataset and it will avoid writing an excessive amount of empty chunks. When I try to append (`mode='a'`, `append_dim` set), I cannot specify `{'write_empty_chunks': False}` and it uses the default value `True` and will write empty chunks.

Example from MCVE:
```
>>> ds.to_zarr('demo_append.zarr', encoding={'test': {'write_empty_chunks': False}})
<xarray.backends.zarr.ZarrStore object at 0x11cb1a6c0>
>>>
>>> import os
>>> os.system('ls demo_append.zarr/test')
0.1.0
0
>>>
>>> ds.to_zarr('demo_append.zarr', mode='a', append_dim='Z', encoding={'test': {'write_empty_chunks': False}})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rileykk/opt/anaconda3/envs/oco-test/lib/python3.11/site-packages/xarray/core/dataset.py", line 2236, in to_zarr
    return to_zarr(  # type: ignore[call-overload,misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rileykk/opt/anaconda3/envs/oco-test/lib/python3.11/site-packages/xarray/backends/api.py", line 1673, in to_zarr
    raise ValueError(
ValueError: variable 'test' already exists, but encoding was provided
>>> ds.to_zarr('demo_append.zarr', mode='a', append_dim='Z')
<xarray.backends.zarr.ZarrStore object at 0x11d53d0e0>
>>> os.system('ls demo_append.zarr/test')
0.1.0	1.0.0	1.0.1	1.1.0	1.1.1
0
```

### What did you expect to happen?

I would expect the `write_empty_chunks` encodings to either be configurable or preserved when appending.

### Minimal Complete Verifiable Example

```Python
import xarray as xr
import numpy as np
import os

d = np.array([np.nan, np.nan, 1.0, np.nan]).reshape((1, 2,2))
ds = xr.Dataset(data_vars={'test': (('Z', 'Y', 'X'), d)})

ds['test'] = ds['test'].chunk((1,1,1))

# 3 chunks in 'test' var fully empty so they should not be written
ds.to_zarr('demo_append.zarr', mode='w', encoding={'test': {'write_empty_chunks': False}})

# Verify only one chunk written
os.system('ls demo_append.zarr/test')

# Error here; cannot specify that we don't want to write empty chunks
ds.to_zarr('demo_append.zarr', mode='a', append_dim='Z', encoding={'test': {'write_empty_chunks': False}})

# Append without specifying encoding
ds.to_zarr('demo_append.zarr', mode='a', append_dim='Z')

# But now we have appended 4 new chunks (5 total) instead of just 1
os.system('ls demo_append.zarr/test')

# Show the chunk shape + that the appended data has 3 empty chunks
xr.open_zarr('demo_append.zarr')
xr.open_zarr('demo_append.zarr').test.to_numpy()
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:10:28) [Clang 15.0.7 ]
python-bits: 64
OS: Darwin
OS-release: 22.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.14.0
libnetcdf: 4.9.2

xarray: 2023.7.0
pandas: 2.0.2
numpy: 1.25.1
scipy: 1.11.1
netCDF4: 1.6.4
pydap: None
h5netcdf: 1.2.0
h5py: 3.9.0
Nio: None
zarr: 2.15.0
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: 1.3.7
dask: 2023.4.0
distributed: 2023.4.0
matplotlib: 3.7.2
cartopy: None
seaborn: None
numbagg: None
fsspec: 0.8.3
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 67.7.2
pip: 23.1.2
conda: None
pytest: None
mypy: None
IPython: 8.12.0
sphinx: None

</details>

**Comment by RKuttruff** [comment]
Looks like this will require `zarr>=2.11` to have an effect; otherwise it will issue a warning of unrecognized kwarg on `to_zarr`. This seems to be what is causing the `min_all_deps` check to fail (+ the fact that the new test cases expect it to work when it shouldn't with that version of `zarr`). Is this something that would be better resolved by a check or bumping the minimum required `zarr` version?
