### ISSUE TITLE
xarray.align can return read-only arrays

### ISSUE THREAD

**Issue by LukeJones123** [pydata/xarray#8274]
### What happened?

The attached code snippet raises "ValueError: output array is read-only" because the d1 array returned from xarray.align is read-only.

### What did you expect to happen?

d1 should not be a read-only. d2 should have been added to it without issue.

### Minimal Complete Verifiable Example

```Python
import numpy as np
import xarray as xr

d1 = xr.DataArray(np.array([]), coords={'dim': []})
d2 = xr.DataArray(np.array([1]), coords={'dim': ['x']})
d1 , d2 = xr.align(d1, d2, join='outer', fill_value=0, copy=True)
d1 += d2
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [X] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [X] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
Traceback (most recent call last):
  File "/home/atest.py", line 7, in <module>
    d1 += d2
  File "/some/where/lib/python3.10/site-packages/xarray/core/_typed_ops.py", line 328, in __iadd__
    return self._inplace_binary_op(other, operator.iadd)
  File "/some/where/lib/python3.10/site-packages/xarray/core/dataarray.py", line 4659, in _inplace_binary_op
    f(self.variable, other_variable)
  File "/some/where/lib/python3.10/site-packages/xarray/core/_typed_ops.py", line 680, in __iadd__
    return self._inplace_binary_op(other, operator.iadd)
  File "/some/where/lib/python3.10/site-packages/xarray/core/variable.py", line 2710, in _inplace_binary_op
    self.values = f(self_data, other_data)
ValueError: output array is read-only
```

### Anything else we need to know?

I suspect this is related to https://github.com/pydata/xarray/issues/3813, i.e. that `align` is calling `expand_dims` behind the scenes. But even if the `expand_dims` aspect is considered a feature rather than a bug, the `DataArray.copy()` required to fix it should be done by `align` since the documentation says it should return a copy, not a view.

### Environment

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.10 (main, Feb  9 2023, 14:42:48) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10)]
python-bits: 64
OS: Linux
OS-release: 4.18.0-372.52.1.el8_6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: ('en_GB', 'UTF-8')
libhdf5: None
libnetcdf: None

xarray: 2023.9.0
pandas: 2.1.1
numpy: 1.26.0
scipy: None
netCDF4: None
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: None
distributed: None
matplotlib: None
cartopy: None
seaborn: None
numbagg: None
fsspec: None
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.5.0
pip: 22.3.1
conda: None
pytest: None
mypy: None
IPython: None
sphinx: None

</details>

**Comment by mathause** [comment]
Interesting case - I guess inplace operations are not used _that_ often.

Simpler repro:

```python
np.broadcast_to(0, (1,)).flags
```
from

https://github.com/pydata/xarray/blob/938579dbf7360c7d760ee7c6d3ffb2753bfa92e4/xarray/core/variable.py#L835

From the docs of `broadcast_to`:

```
broadcast : array
    A readonly view on the original array with the given shape. It is
    typically not contiguous. Furthermore, more than one element of a
    broadcasted array may refer to a single memory location.
```

So we probably need to explitely call `copy` on it. See:

```python
np.broadcast_to(0, (1,)).copy().flags
```

However, I am not sure where the copy should happen. Either in `_getitem_with_mask` or conditionally in 

https://github.com/pydata/xarray/blob/938579dbf7360c7d760ee7c6d3ffb2753bfa92e4/xarray/core/alignment.py#L73
