### ISSUE TITLE
Extend DatetimeAccessor with `snap`-method

### ISSUE THREAD

**Issue by maawoo** [pydata/xarray#8378]
### Is your feature request related to a problem?

With satellite remote sensing data, you sometimes end up with a blown up DataArray/Dataset because individual acquisitions have been saved in slices:

![group_acq_slices_1](https://github.com/pydata/xarray/assets/56583917/e439c153-b0f6-4025-85b2-9b31e1daf784)

One could then aggregate these slices with something like this: 

```python
ds.coords['time'] = ds.time.dt.floor('1H')  # or .ceil
ds = ds_copy.groupby('time').mean()
```

However, this would miss cases where one slice has been acquired before and the other after a specific hour. The  [`pandas.DatetimeIndex.snap`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.snap.html) method could be a good alternative for such cases.

### Describe the solution you'd like

In addition to the [`floor`](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.dt.floor.html), [`ceil`](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.dt.ceil.html) and [`round`](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.dt.round.html) methods, it would be great to also implement [`pandas.DatetimeIndex.snap`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.snap.html).

**Comment by dcherian** [comment]
Great idea! We use pandas under the hood so this is a fairly easy change. A Pull Request would be very welcome. See https://github.com/pydata/xarray/blob/main/xarray/core/accessor_dt.py The trick will be to support CFTimeIndex too, but hopefully that's not too hard

**Comment by maawoo** [comment]
I already gave it a quick try by adding snap as a new method just like floor, ceil and round. But then got stuck and didn't find a quick solution. I guess your advice on supporting CFTimeIndex is related? 

```python
Traceback (most recent call last):
  File "/Users/marcowo/mambaforge/envs/dev_sdc_env/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-199f66fadbd4>", line 25, in <module>
    da.time.dt.snap('1H')
  File "/Users/marcowo/mambaforge/envs/dev_sdc_env/lib/python3.11/site-packages/xarray/core/accessor_dt.py", line 315, in snap
    return self._tslib_round_accessor("snap", freq)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcowo/mambaforge/envs/dev_sdc_env/lib/python3.11/site-packages/xarray/core/accessor_dt.py", line 248, in _tslib_round_accessor
    result = _round_field(_index_or_data(self._obj), name, freq)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcowo/mambaforge/envs/dev_sdc_env/lib/python3.11/site-packages/xarray/core/accessor_dt.py", line 190, in _round_field
    return _round_through_series_or_index(values, name, freq)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcowo/mambaforge/envs/dev_sdc_env/lib/python3.11/site-packages/xarray/core/accessor_dt.py", line 153, in _round_through_series_or_index
    method = getattr(values_as_series.dt, name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DatetimeProperties' object has no attribute 'snap'
```

https://github.com/pydata/xarray/blob/bb489fa7fbdf5017c1c31a7a8344477c9991c6eb/xarray/core/accessor_dt.py#L153
