### ISSUE TITLE
xarray and pyinstaller

### ISSUE THREAD

**Issue by happymvd** [pydata/xarray#8912]
### What is your issue?

I am working on a Windows 11 computer with Python 3.11.9 installed as the only version of Python
I am working in Virtual Studio Code
I have created and activated a venv virtual environment for my project (not a conda one)
I used the pip command to install xarray into the virtual environment
I have a test script called Testing.py and the only thing it does is import xarray as xr and then it prints a message to the terminal window
This works 100% in python in the VSC terminal window
I then issue the following command
  pyinstaller --onefile Testing.py

This creates a file called Testing.exe for me
When I run Testing.exe I get the following error message

**Traceback (most recent call last):
  File "importlib\metadata\__init__.py", line 563, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Testing.py", line 20, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xarray\__init__.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xarray\testing\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xarray\testing\assertions.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xarray\core\duck_array_ops.py", line 36, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xarray\core\dask_array_ops.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xarray\core\nputils.py", line 14, in <module>
  File "xarray\namedarray\utils.py", line 60, in module_available
  File "importlib\metadata\__init__.py", line 1009, in version
  File "importlib\metadata\__init__.py", line 982, in distribution
  File "importlib\metadata\__init__.py", line 565, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for numpy
[15596] Failed to execute script 'Testing' due to unhandled exception!**

Please, is there anyone who can suggest what I need to do to get around this problem .... I need to distribute my project when it is complete

**Comment by max-sixty** [comment]
Unfortunately this seems like a pyinstaller issue — it looks like even numpy can't be imported. I'll close, but if anyone has ideas feel free to add thoughts.

**Comment by happymvd** [comment]
SOLUTION - when xarray is imported in a script you have to include "**--copy-metadata numpy**" in the command line when pyinstaller is used
