### ISSUE TITLE
docs builds are broken

### ISSUE THREAD

**Issue by dcherian** [pydata/xarray#9774]
### What happened?

```

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/9766/lib/python3.12/site-packages/nbsphinx/__init__.py", line 634, in parse
    rststring, resources = exporter.from_notebook_node(nb, resources)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/9766/lib/python3.12/site-packages/nbsphinx/__init__.py", line 397, in from_notebook_node
    nb, resources = pp.preprocess(nb, resources)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/9766/lib/python3.12/site-packages/nbconvert/preprocessors/execute.py", line 103, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/9766/lib/python3.12/site-packages/nbconvert/preprocessors/execute.py", line 124, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/9766/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/9766/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/9766/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/9766/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ds = xr.tutorial.load_dataset("era5-2mt-2019-03-uk.grib", engine="cfgrib")
------------------


[0;31mHTTPError[0m: 403 Client Error: Forbidden for url: https://raw.githubusercontent.com/pydata/xarray-data/master/era5-2mt-2019-03-uk.grib

```

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue in xarray.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] Verifiable example — the example copy & pastes into an IPython prompt or [Binder notebook](https://mybinder.org/v2/gh/pydata/xarray/main?urlpath=lab/tree/doc/examples/blank_template.ipynb), returning the result.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.
- [ ] Recent environment — the issue occurs with the latest version of xarray and its dependencies.

### Environment

<details>

</details>

**Comment by kmuehlbauer** [comment]
This issue is not only affecting xarray, also other projects hosted on RTD experience these download issues. Not idea how to tackle this, since the data downloads perfectly fine locally. 

`pooch` also didn't have an update recently, ruling that out as an issue. Maybe some other dependencies have changed in the network stack?

**Comment by kmuehlbauer** [comment]
XRef: 

- https://github.com/scipy/scipy/issues/21879
- https://github.com/openradar/xradar/pull/240#issuecomment-2474905416

**Comment by kmuehlbauer** [comment]
This is some weird upstream issue between RTD and GitHub AFAICT, see https://github.com/readthedocs/readthedocs.org/issues/11763#issuecomment-2476333955 for a summary.

**Comment by phofl** [comment]
Dask fixed this here: https://github.com/dask/dask-sphinx-theme/pull/91
